from datetime import date, datetime
import os
import subprocess
import sys
import time
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

from dashboard_services.api import get_nfl_state
from utils.paths import DATA_DIR, CACHE_DIR


# ---------------------------------------------------------------------------
# Cleanup: delete old date-stamped files left from before the undated migration
# ---------------------------------------------------------------------------

import re
_DATED_PATTERN = re.compile(r'_\d{4}-\d{2}-\d{2}')


def cleanup_dated_files() -> int:
    """Delete old date-stamped stale files from the data/ directory.

    Only scans DATA_DIR (data/).  CACHE_DIR is intentionally excluded because
    cache/sleeper_stats/ holds dated historical stats files
    (e.g. sleeper_stats_s2025_w1_2026-04-09.json) that are permanent game-log
    data — they cannot be regenerated by the cron and must not be deleted.
    """
    removed = 0
    search_dirs = [DATA_DIR]
    for base in search_dirs:
        if not Path(base).exists():
            continue
        for p in Path(base).rglob("*"):
            if p.is_file() and _DATED_PATTERN.search(p.stem):
                try:
                    p.unlink()
                    print(f"[cron] Removed dated file: {p}")
                    removed += 1
                except Exception as e:
                    print(f"[cron] Could not remove {p}: {e}")
    return removed


# ---------------------------------------------------------------------------
# Freshness guards - skip expensive steps that already ran today
# ---------------------------------------------------------------------------

def _today() -> date:
    return date.today()


def _file_fresh_today(path: Path) -> bool:
    """True if the file exists and was last modified today."""
    if not path.exists():
        return False
    return date.fromtimestamp(path.stat().st_mtime) == _today()


def _model_values_fresh() -> bool:
    mv = DATA_DIR / "model_values.json"
    if not _file_fresh_today(mv):
        return False
    # If any vendor CSV is newer than model_values.json, the model needs a rebuild
    # even if it was already written today (it was built from stale data).
    mv_mtime = mv.stat().st_mtime
    for _csv in ("fantasycalc_api_values.csv", "dynastyprocess_values.csv"):
        _p = DATA_DIR / _csv
        if _p.exists() and _p.stat().st_mtime > mv_mtime:
            return False
    return True


def _vendor_values_fresh() -> bool:
    return (
        _file_fresh_today(DATA_DIR / "fantasycalc_api_values.csv") and
        _file_fresh_today(DATA_DIR / "fantasycalc_sf_api_values.csv") and
        _file_fresh_today(DATA_DIR / "dynastyprocess_values.csv")
    )


def _usage_table_fresh() -> bool:
    return _file_fresh_today(DATA_DIR / "usage_table.json")


def _model_mtime() -> float:
    """Return mtime of model_values.json, or 0 if missing."""
    mv = DATA_DIR / "model_values.json"
    return mv.stat().st_mtime if mv.exists() else 0.0


def _player_values_fresh() -> bool:
    try:
        from dashboard_services.db import get_conn
        with get_conn() as conn:
            row = conn.execute(
                "SELECT MAX(last_updated) AS t FROM player_values"
            ).fetchone()
        if row and row["t"]:
            t = row["t"]
            db_date = t.date() if hasattr(t, "date") else t
            if db_date != _today():
                return False
            # Also stale if model_values.json was rewritten after the last DB save.
            # Use .timestamp() so timezone-aware datetimes convert correctly;
            # calendar.timegm(timetuple()) strips tz info and is wrong on non-UTC hosts.
            try:
                db_ts = t.timestamp()
            except Exception:
                db_ts = 0
            if _model_mtime() > db_ts:
                return False
            return True
    except Exception:
        pass
    return False


def _trade_intel_fresh() -> bool:
    try:
        from dashboard_services.db import get_conn
        with get_conn() as conn:
            row = conn.execute(
                "SELECT MAX(last_crawled_at) AS t FROM trade_intel_leagues "
                "WHERE last_crawled_at IS NOT NULL"
            ).fetchone()
        if row and row["t"]:
            t = row["t"]
            return (t.date() if hasattr(t, "date") else t) == _today()
    except Exception:
        pass
    return False


def _wls_fresh() -> bool:
    try:
        from dashboard_services.db import get_conn
        with get_conn() as conn:
            row = conn.execute(
                "SELECT MAX(last_updated) AS t FROM player_values "
                "WHERE calibration_source = 'trade_wls'"
            ).fetchone()
        if row and row["t"]:
            t = row["t"]
            wls_date = t.date() if hasattr(t, "date") else t
            if wls_date != _today():
                return False
            # Also stale if model_values.json was rebuilt after the last WLS run
            # (the new model would make a different prior for WLS).
            # Use .timestamp() so timezone-aware datetimes convert correctly;
            # calendar.timegm(timetuple()) strips tz info and is wrong on non-UTC hosts.
            try:
                wls_ts = t.timestamp()
            except Exception:
                wls_ts = 0
            if _model_mtime() > wls_ts:
                return False
            return True
    except Exception:
        pass
    return False


# ---------------------------------------------------------------------------
# Subprocess runner - each step gets a fresh process so memory fully releases
# ---------------------------------------------------------------------------

def _run_step(code: str, step_name: str, timeout: int = 3600) -> bool:
    """
    Run Python code in a fresh interpreter subprocess.
    stdout/stderr flow through. Returns True on success.
    Memory from the subprocess is fully released when it exits.
    """
    print(f"[cron] -> {step_name}")
    try:
        result = subprocess.run(
            [sys.executable, "-c", code],
            timeout=timeout,
            env=os.environ.copy(),
        )
        if result.returncode != 0:
            print(f"[cron] {step_name} exited with code {result.returncode}")
            return False
        return True
    except subprocess.TimeoutExpired:
        print(f"[cron] {step_name} timed out after {timeout}s")
        return False
    except Exception as e:
        print(f"[cron] {step_name} failed to launch: {e}")
        return False


def main():
    state = get_nfl_state() or {}
    season = int(state.get("season") or date.today().year)
    week = int(state.get("week") or 0)
    season_type = str(state.get("season_type", "")).lower().strip()
    today_weekday = date.today().weekday()  # 6 = Sunday

    print(f"[cron] Daily run starting - Season {season}, Week {week}")

    n_cleaned = cleanup_dated_files()
    if n_cleaned:
        print(f"[cron] Cleaned up {n_cleaned} old dated file(s)")

    # ------------------------------------------------------------------ #
    # Step 1: Vendor data + usage table                                   #
    # ------------------------------------------------------------------ #
    if _vendor_values_fresh() and _usage_table_fresh():
        print("[cron] Vendor + usage data already fresh today, skipping")
    else:
        _run_step(f"""
from dotenv import load_dotenv; load_dotenv()
from data_building.build_daily_value_table import build_daily_data
build_daily_data({season!r}, {week!r})
""", "build_daily_data")

    # ------------------------------------------------------------------ #
    # Step 2: Weekly projections                                         #
    # In-season (reg/post): refresh current + next week daily            #
    # Offseason: refresh all 18 weeks, but only once per week            #
    # ------------------------------------------------------------------ #
    in_season = season_type in ("reg", "post")
    if in_season:
        _proj_weeks = sorted(set([week, min(week + 1, 18)]))
        _proj_fresh = all(
            _file_fresh_today(Path(f"{CACHE_DIR}/projections/projections_s{season}_w{w}.json"))
            for w in _proj_weeks
        )
    else:
        _proj_weeks = list(range(1, 19))
        _proj_fresh = all(
            (
                (p := Path(f"{CACHE_DIR}/projections/projections_s{season}_w{w}.json")).exists()
                and (date.today() - date.fromtimestamp(p.stat().st_mtime)).days < 7
            )
            for w in _proj_weeks
        )

    if _proj_fresh:
        print(f"[cron] Projections already fresh ({'today' if in_season else 'this week'}), skipping")
    else:
        _run_step(f"""
from dotenv import load_dotenv; load_dotenv()
from utils.utils import fetch_week_projections, save_week_projections
for w in {_proj_weeks!r}:
    data = fetch_week_projections({season!r}, w)
    save_week_projections({season!r}, w, data)
    print(f"[cron] Projections week {{w}}: {{len(data)}} players")
""", "fetch_weekly_projections")

    # ------------------------------------------------------------------ #
    # Step 4: Advanced metrics                                            #
    # ------------------------------------------------------------------ #
    _run_step(f"""
from dotenv import load_dotenv; load_dotenv()
from datetime import datetime, date
from dashboard_services.api import get_nfl_state
from data_building.advanced_metrics import calculate_player_metrics, finalize_role_scores_v2, save_metrics_snapshot, load_matchup_ease
from utils.utils import load_usage_table

nfl_state = get_nfl_state() or {{}}
season_type = str(nfl_state.get("season_type", "")).lower().strip()
is_offseason = season_type == "off"
current_season = int(nfl_state.get("season") or datetime.now().year)

usage_table = load_usage_table()
if not usage_table:
    print("[cron] No usage table found, skipping advanced metrics")
else:
    players_with_games = sum(1 for p in usage_table if p.get("usage", {{}}).get("games", 0) > 0)
    if players_with_games == 0 and is_offseason:
        print("[cron] Offseason detected, skipping advanced metrics")
    else:
        metrics_list = []
        failed_count = 0
        ease_map = load_matchup_ease(current_season)
        for player in usage_table:
            player_id = player.get("id")
            position = player.get("position")
            usage = player.get("usage", {{}})
            team = player.get("team") or ""
            if not player_id or not position or not usage or usage.get("games", 0) == 0:
                continue
            try:
                m = calculate_player_metrics(player_id, usage, position)
                m["nfl_team"] = team or None
                m["schedule_ease"] = (ease_map.get(team) or {{}}).get(position) if team else None
                metrics_list.append(m)
            except Exception:
                failed_count += 1
        # Role score v2: percentile within position from team-relative shares
        # (needs the whole cohort, so it runs once after the per-player loop).
        finalize_role_scores_v2(metrics_list, usage_table)
        if metrics_list:
            save_metrics_snapshot(metrics_list, date.today().isoformat(), season=current_season)
            print(f"[cron] Advanced metrics: {{len(metrics_list)}} processed, {{failed_count}} failed")
        else:
            print("[cron] No advanced metrics calculated")

    # Air yards from stats CSV – runs regardless of offseason gate.
    # During the offseason current_season is the upcoming year (no CSV yet),
    # so try the prior season as a fallback.
    try:
        from data_building.advanced_metrics import import_air_yards_from_stats_csv
        from pathlib import Path
        from utils.paths import DATA_DIR
        _ay_season = current_season
        if not Path(DATA_DIR, "cache", f"stats_player_reg_{{_ay_season}}.csv").exists():
            _ay_season = current_season - 1
        updated = import_air_yards_from_stats_csv(_ay_season)
        print(f"[cron] Air yards import: {{updated}} rows updated for season {{_ay_season}}")
    except Exception as _e:
        print(f"[cron] Air yards import failed: {{_e}}")
""", "build_daily_advanced_metrics")

    # ------------------------------------------------------------------ #
    # Step 4a: Weekly usage metrics (snap/target share per week)          #
    # Powers usage risers, trend sparklines, and start/sit usage factor.  #
    # ------------------------------------------------------------------ #
    _run_step("""
from dotenv import load_dotenv; load_dotenv()
from datetime import datetime
from dashboard_services.api import get_nfl_state
from data_building.weekly_metrics import build_weekly_metrics

nfl_state = get_nfl_state() or {{}}
season_type = str(nfl_state.get("season_type", "")).lower().strip()
current_season = int(nfl_state.get("season") or datetime.now().year)
if season_type == "off":
    print("[cron] Offseason - refreshing weekly metrics for prior season")
    n = build_weekly_metrics(current_season - 1)
else:
    n = build_weekly_metrics(current_season)
print(f"[cron] Weekly metrics: {{n}} rows upserted")
""", "build_weekly_metrics")

    # ------------------------------------------------------------------ #
    # Step 4b: Defense-vs-position matchup ratings (z-scores)             #
    # Powers the Schedule Assistant rankings / ease scores.               #
    # Only rebuilt on Wednesdays during the regular/post season so each   #
    # week's new game data is captured after the Tuesday final box-score  #
    # update. Skipped entirely in the offseason.                          #
    # ------------------------------------------------------------------ #
    if not in_season:
        print("[cron] Matchup ratings skipped - offseason")
    elif today_weekday != 2:  # 0=Mon … 2=Wed … 6=Sun
        print(f"[cron] Matchup ratings skipped - not Wednesday (weekday={today_weekday})")
    else:
        _run_step(f"""
from dotenv import load_dotenv; load_dotenv()
from data_building.matchup_ratings import build_matchup_ratings, out_path
res = build_matchup_ratings({season!r})
print(f"[cron] Matchup ratings: {{len(res.get('ratings', {{}}))}} teams -> {{out_path({season!r})}}")
""", "build_matchup_ratings", timeout=900)

    # ------------------------------------------------------------------ #
    # Step 5: Model values                                                #
    # ------------------------------------------------------------------ #
    if _model_values_fresh():
        print("[cron] Model values already built today, skipping")
    else:
        _run_step("""
from dotenv import load_dotenv; load_dotenv()
from data_building.build_daily_value_table import build_daily_model_values
build_daily_model_values()
""", "build_daily_model_values")

    # ------------------------------------------------------------------ #
    # Step 3b: EMA snapshot — always run so sf_value is always written   #
    # even on days when model_values.json is already fresh (step 3       #
    # skipped).  record_model_value_snapshot's min_change_pct guard      #
    # skips rows whose values haven't moved, so double-running on model- #
    # rebuild days is safe.                                               #
    # ------------------------------------------------------------------ #
    _run_step("""
from dotenv import load_dotenv; load_dotenv()
from utils.utils import load_model_value_table
from data_building.player_value_history import record_model_value_snapshot
tbl = load_model_value_table(apply_calibration=False) or []
n = record_model_value_snapshot(tbl)
print(f"[cron] EMA snapshot wrote {n} rows (value + sf_value + size variants)")
""", "record_model_value_snapshot")

    _run_step("""
from dotenv import load_dotenv; load_dotenv()
from utils.push_notifications import notify_value_drops
notify_value_drops()
print("[cron] Value drop notifications dispatched")
""", "notify_value_drops")

    _run_step("""
from dotenv import load_dotenv; load_dotenv()
from utils.push_notifications import notify_waiver_candidates, notify_playoff_odds
notify_waiver_candidates()
notify_playoff_odds()
print("[cron] Waiver + playoff-odds notifications dispatched")
""", "notify_waiver_playoff")

    _run_step("""
from dotenv import load_dotenv; load_dotenv()
from utils.push_notifications import notify_top_movers
notify_top_movers()
print("[cron] Weekly top-movers notification dispatched (throttled to 7 days)")
""", "notify_top_movers")

    _run_step("""
from dotenv import load_dotenv; load_dotenv()
from utils.push_notifications import notify_recap_ready, notify_matchup_preview, notify_standings_update
notify_recap_ready()
notify_matchup_preview()
notify_standings_update()
print("[cron] Recap/matchup/standings notifications dispatched")
""", "notify_weekly_game")

    # ------------------------------------------------------------------ #
    # Step 4: Save player values to DB                                   #
    # ------------------------------------------------------------------ #
    if _player_values_fresh():
        print("[cron] Player values already saved to DB today, skipping")
    else:
        _run_step("""
from dotenv import load_dotenv; load_dotenv()
from data_building.update_player_values_with_rankings import update_player_values_with_rankings
n = update_player_values_with_rankings()
print(f"[cron] Saved {n} player values")
""", "update_player_values_with_rankings")

    # ------------------------------------------------------------------ #
    # Step 4b: Sync EMA values from player_value_history → player_values #
    # EMA-smoothed values from record_model_value_snapshot() (step 3)   #
    # are copied into player_values.value_1qb, replacing the raw model  #
    # values written by step 4.  Calibrated columns are cleared so the  #
    # EMA values are immediately visible site-wide.                      #
    # ------------------------------------------------------------------ #
    _run_step("""
from dotenv import load_dotenv; load_dotenv()
from data_building.build_daily_value_table import sync_history_to_player_values
n = sync_history_to_player_values()
print(f"[cron] Synced {n} EMA values from player_value_history to player_values")
""", "sync_ema_to_player_values")

    # ------------------------------------------------------------------ #
    # Step 5a: Archetype cache export (WR/TE role-fit context for        #
    # breakout engine). Runs unconditionally so the cache stays current  #
    # as PFF advanced metrics are refreshed throughout the offseason.    #
    # Exports the STATS season (season-1): the breakout build scores from #
    # the prior completed season's usage and loads archetype_{season-1}. #
    # The current season has no game data yet (0 rows), so exporting it   #
    # would write an empty cache and silently disable all role-fit labels.#
    # ------------------------------------------------------------------ #
    _archetype_season = season - 1
    _run_step(f"""
from dotenv import load_dotenv; load_dotenv()
import sys, os; sys.path.insert(0, os.getcwd())
from scripts.export_archetype_cache import run as export_archetype
n = export_archetype({_archetype_season!r})
print(f"[cron] Archetype cache: {{n}} WR/TE profiles -> cache/archetype_{_archetype_season!r}.json")
""", "export_archetype_cache")

    # ------------------------------------------------------------------ #
    # Step 5b: Breakout candidates                                       #
    # ------------------------------------------------------------------ #
    _run_step(f"""
from dotenv import load_dotenv; load_dotenv()
from datetime import date
today = date.today()
if today.month in (1, 2) or (today.month == 3 and today.day < 15):
    print("[cron] Breakout skipped - playoff/early offseason period")
else:
    from data_building.breakout_engine.calculate_breakouts_with_real_data import main as run_breakouts
    result = run_breakouts()
    print(f"[cron] Breakout: {{result}}")
""", "build_daily_breakout_scores")

    _run_step("""
from dotenv import load_dotenv; load_dotenv()
from utils.push_notifications import notify_breakout_roster
notify_breakout_roster()
print("[cron] Breakout roster notifications dispatched")
""", "notify_breakout_roster")

    # ------------------------------------------------------------------ #
    # Step 6: Weekly rookie data (Sundays only, off/pre season)          #
    # ------------------------------------------------------------------ #
    ROOKIE_PIPELINE_PAUSED = True
    if not ROOKIE_PIPELINE_PAUSED and today_weekday == 6 and season_type not in ("reg", "post"):
        _run_step(f"""
from dotenv import load_dotenv; load_dotenv()
from data_building.rookie_pipeline.pipeline import run_rookie_pipeline, get_active_rookie_class
from data_building.rookie_pipeline.rookie_evaluation_pipeline import run_rookie_evaluation_pipeline
year = get_active_rookie_class()
print(f"[cron] Weekly rookie refresh - {{year}} draft class")
eval_result = run_rookie_evaluation_pipeline(year)
print(f"[cron] Eval: {{eval_result.get('profile_count', 0)}} profiles")
result = run_rookie_pipeline(year)
print(f"[cron] Scoring: {{len(result.get('prospects', []))}} prospects")
""", "build_weekly_rookie_data")
    else:
        reason = "paused" if ROOKIE_PIPELINE_PAUSED else f"weekday={today_weekday}, season_type={season_type!r}"
        print(f"[cron] Rookie weekly run skipped - {reason}")

    # ------------------------------------------------------------------ #
    # Step 7: Trade intel discovery + crawl + analytics                  #
    # Split into three subprocesses so each step's memory is fully       #
    # released before the next one starts.                                #
    # ------------------------------------------------------------------ #
    if _trade_intel_fresh():
        print("[cron] Trade intel already crawled today, skipping discovery + crawl")
    else:
        _run_step(f"""
from dotenv import load_dotenv; load_dotenv()
from data_building.trade_intel.league_discovery import run_discovery, backfill_superflex
backfilled = backfill_superflex(batch_size=500)
if backfilled:
    print(f"[cron] Backfilled is_superflex for {{backfilled}} leagues")
discovered = run_discovery(target=200)
print(f"[cron] Trade intel: discovered {{discovered}} new leagues")
""", "trade_intel_discovery")

        _run_step(f"""
from dotenv import load_dotenv; load_dotenv()
from data_building.trade_intel.trade_crawler import run_crawl
crawl_result = run_crawl(batch_size=50, workers=2)
print(f"[cron] Trade intel: {{crawl_result}}")
""", "trade_intel_crawl")

        _run_step(f"""
from dotenv import load_dotenv; load_dotenv()
from data_building.trade_intel.analytics import run_analytics
analytics_result = run_analytics(season={season!r})
print(f"[cron] Trade intel analytics: {{analytics_result}}")
""", "trade_intel_analytics")

        _run_step("""
from dotenv import load_dotenv; load_dotenv()
from utils.push_notifications import notify_rival_trades
notify_rival_trades()
print("[cron] Rival trade notifications dispatched")
""", "notify_rival_trades")

    # ------------------------------------------------------------------ #
    # Step 8: Draft ADP crawl                                            #
    # ------------------------------------------------------------------ #
    _run_step("""
from dotenv import load_dotenv; load_dotenv()
from data_building.trade_intel.draft_adp_crawler import run_draft_adp_crawl
result = run_draft_adp_crawl(batch_size=150, workers=2, crawl_mode="both", recrawl_days=30)
print(f"[cron] Draft ADP: {result}")
""", "draft_adp_crawl")

    # ------------------------------------------------------------------ #
    # Step 9: WLS calibration - one subprocess per combo so numpy        #
    # matrices and trade data are fully released between runs.            #
    # ------------------------------------------------------------------ #
    if _wls_fresh():
        print("[cron] WLS calibration already ran today, skipping")
    else:
        for _lt, _lt_name, _sz in [
            (2, "dynasty", 10),
            (2, "dynasty", 12),
            (1, "redraft", 10),
            (1, "redraft", 12),
        ]:
            _run_step(f"""
from dotenv import load_dotenv; load_dotenv()
from data_building.trade_intel.trade_value_model import run_trade_value_model
try:
    res = run_trade_value_model(season={season!r}, league_type={_lt}, league_size={_sz})
    print(f"[cron] WLS {_lt_name} {_sz}-team: {{res}}")
except Exception as e:
    print(f"[cron] WLS {_lt_name} {_sz}-team failed: {{e}}")
""", f"wls_{_lt_name}_{_sz}team")

    # ------------------------------------------------------------------ #
    # Step 10: Calibrated history snapshot                               #
    # ------------------------------------------------------------------ #
    _run_step("""
from dotenv import load_dotenv; load_dotenv()
from data_building.build_daily_value_table import record_calibrated_history_snapshot
n = record_calibrated_history_snapshot()
print(f"[cron] Calibrated history snapshot: {n} players")
""", "record_calibrated_history_snapshot")

    # ------------------------------------------------------------------ #
    # Step 11: Flush in-memory value cache                               #
    # WLS (step 9) updates calibrated_value_sf AFTER the cache may have  #
    # been repopulated mid-cron.  Flushing here ensures the next request  #
    # reads the final WLS-calibrated values, not a stale mid-cron state.  #
    # Requires APP_URL and CRON_SECRET env vars; skipped silently if      #
    # either is missing.                                                   #
    # ------------------------------------------------------------------ #
    _app_url    = os.environ.get("APP_URL", "").rstrip("/")
    _cron_secret = os.environ.get("CRON_SECRET", "")
    if _app_url and _cron_secret:
        try:
            import urllib.request, json as _json
            _body = _json.dumps({"secret": _cron_secret}).encode()
            _req  = urllib.request.Request(
                f"{_app_url}/api/flush-value-cache",
                data=_body,
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(_req, timeout=10) as _resp:
                print(f"[cron] Cache flush: HTTP {_resp.status}")
        except Exception as _flush_err:
            print(f"[cron] Cache flush failed (non-fatal): {_flush_err}")
    else:
        print("[cron] Cache flush skipped — APP_URL or CRON_SECRET not set")

    print(f"[cron] Daily run completed - Season {season}, Week {week}")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"[cron] Daily run failed: {e}")
        import traceback
        traceback.print_exc()
        try:
            from utils.email_notifications import send_cron_failure_notification
            from dashboard_services.api import get_nfl_state
            state = get_nfl_state() or {}
            send_cron_failure_notification(e, {
                'season': state.get("season"),
                'week': state.get("week"),
                'timestamp': datetime.now().isoformat()
            })
        except Exception:
            pass
