---
services:
  - type: web
    name: brfantasy
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python -m playwright install chromium
    startCommand: python startup.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: brfantasy-db
          property: connectionString
      - key: EMAIL_USER
        value: kjenkins3232@gmail.com
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: RECIPIENT_EMAIL
        value: kjenkins3232@gmail.com
        sync: false
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: PYTHON_ENV
        value: production
    autoDeploy: true
  - type: cron
    name: daily-job
    runtime: python
    schedule: 0 8 * * *
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python cron_daily.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: brfantasy-db
          property: connectionString
      - key: EMAIL_USER
        value: kjenkins3232@gmail.com
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: RECIPIENT_EMAIL
        value: kjenkins3232@gmail.com
        sync: false
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: PYTHON_ENV
        value: production

databases:
  - name: brfantasy-db
    databaseName: brfantasy
    user: brfantasy_user
    plan: starter