"""Historical NFL team resolution for a player by season (and week).

Game logs and the advanced-metrics team filter both need to know which team a
player was on *during a past season* - not their current team. Using the current
team (from the players index) is wrong for anyone who changed teams: e.g. Mike
Evans (Sleeper 2216) signed with San Francisco this offseason, so his 2025 game
logs showed SF's opponents even though he played all of 2025 for Tampa Bay, and
the adv-metrics "Tampa Bay" filter dropped him entirely.

Resolution order, best source first:

  1. Per-week team map (cache/player_history/weekly_team_s{season}.json), built
     offline from nfl_data_py per-week rosters (the team a player was on each
     week). This is the accurate source and handles *mid-season* trades.
  2. Per-season team from player_history_{season}.parquet (already on disk). This
     is only a rough last resort: the parquet's team column is a *current-roster*
     snapshot stamped onto every season, not the historical season team, so it is
     wrong for anyone who has since changed teams. Used only when the weekly map
     is unavailable for a season.
  3. None -> callers fall back to the players-index current team (old behavior).

The weekly map is generated by cron (build_weekly_team_map); it needs network
access to nfl_data_py, so it is never built at request time. It covers every
season the game logs show, so source #2 should rarely be reached.
"""
from __future__ import annotations

import json
import logging
import os
import time
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)

_HISTORY_DIR = Path("cache") / "player_history"

# The app is inconsistent about a few team codes: the NFL schedule and nflverse
# use LA / WAS / JAX, while the players index uses LAR / WSH. Team resolution
# feeds two consumers that must agree - game-log opponent matching (compares
# against the schedule) and the adv-metrics team filter/pool - so we canonicalise
# every resolved team to the schedule/nflverse form. Only maps these fixed,
# time-invariant display variants; historical relocations (OAK/SD/STL) are left
# alone because both nflverse and the period's schedule already agree on them.
_TEAM_ALIASES = {"LAR": "LA", "WSH": "WAS", "JAC": "JAX"}


def canon_team(t) -> str:
    """Normalise a team code to the schedule/nflverse convention (LA/WAS/JAX)."""
    s = str(t or "").strip().upper()
    return _TEAM_ALIASES.get(s, s)

# In-process caches keyed by season.
_WEEKLY_MAP_CACHE: Dict[int, tuple] = {}   # season -> (ts, {sid: {week: team}})
_SEASON_MAP_CACHE: Dict[int, tuple] = {}   # season -> (ts, {sid: team})
_SEASON_MAP_TTL = 900.0
_WEEKLY_MAP_TTL = 900.0


def weekly_team_map_path(season: int) -> Path:
    return _HISTORY_DIR / f"weekly_team_s{int(season)}.json"


def _init_week_team_table(conn) -> None:
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS player_week_team (
            player_id TEXT    NOT NULL,
            season    INTEGER NOT NULL,
            week      INTEGER NOT NULL,
            team      TEXT    NOT NULL,
            PRIMARY KEY (player_id, season, week)
        )
        """
    )


def _load_week_team_from_db(season: int) -> Optional[Dict[str, Dict[int, str]]]:
    """Per-week team map for a season from the shared DB, or None if the DB is
    unavailable. The DB is the source of truth on Render, where cron (writer) and
    the web service (reader) run in separate containers that do not share a
    filesystem - a local JSON file never reaches the web service."""
    try:
        from dashboard_services.db import get_conn
    except Exception:
        return None
    try:
        with get_conn() as conn:
            # Read-only: no CREATE (the web-service DB role may lack it). If the
            # table doesn't exist yet (cron hasn't run), this raises and we fall
            # back to the file.
            rows = conn.execute(
                "SELECT player_id, week, team FROM player_week_team WHERE season = %s",
                (int(season),),
            ).fetchall()
    except Exception:
        logger.debug("week-team DB read unavailable for %s", season, exc_info=True)
        return None
    out: Dict[str, Dict[int, str]] = {}
    for r in rows:
        sid = str(r["player_id"])
        team = canon_team(r["team"])
        try:
            wk = int(r["week"])
        except (TypeError, ValueError):
            continue
        if sid and team:
            out.setdefault(sid, {})[wk] = team
    return out


def load_weekly_team_map(season: int) -> Dict[str, Dict[int, str]]:
    """{sleeper_id: {week:int -> team:str}} for a season, or {} if not built.

    Reads the shared DB first (so the web service sees what cron built), falling
    back to the local JSON file for environments without a DB (tests, one-off
    scripts). Cached in-process with a short TTL.
    """
    now = time.time()
    cached = _WEEKLY_MAP_CACHE.get(int(season))
    if cached and now - cached[0] < _WEEKLY_MAP_TTL:
        return cached[1]

    db = _load_week_team_from_db(season)
    if db:
        _WEEKLY_MAP_CACHE[int(season)] = (now, db)
        return db

    out: Dict[str, Dict[int, str]] = {}
    try:
        with open(weekly_team_map_path(season)) as f:
            raw = json.load(f)
        for sid, weeks in (raw or {}).items():
            if not isinstance(weeks, dict):
                continue
            wk_map: Dict[int, str] = {}
            for wk, team in weeks.items():
                try:
                    if team:
                        wk_map[int(wk)] = canon_team(team)
                except (TypeError, ValueError):
                    continue
            if wk_map:
                out[str(sid)] = wk_map
    except FileNotFoundError:
        pass
    except Exception:
        logger.debug("weekly_team_map file load failed for %s", season, exc_info=True)
    _WEEKLY_MAP_CACHE[int(season)] = (now, out)
    return out


def season_team_map(season: int) -> Dict[str, str]:
    """{sleeper_id: team} from the season player_history parquet. Rough last
    resort only: the parquet's team is a current-roster snapshot, not the
    historical season team, so it is wrong for players who have changed teams.
    Prefer the per-week map; this is used only when that is unavailable. Empty
    dict if the history file is unavailable."""
    now = time.time()
    cached = _SEASON_MAP_CACHE.get(int(season))
    if cached and now - cached[0] < _SEASON_MAP_TTL:
        return cached[1]
    out: Dict[str, str] = {}
    try:
        from data_building.external_data.player_history import load_player_history_df
        df = load_player_history_df(int(season))
        if df is not None and not df.empty and "sleeper_id" in df.columns and "team" in df.columns:
            for sid, team in zip(df["sleeper_id"], df["team"]):
                if sid is None or team is None:
                    continue
                s = str(sid).strip()
                t = canon_team(team)
                if s and t and t != "NAN":
                    out[s] = t
    except Exception:
        logger.debug("season_team_map load failed for %s", season, exc_info=True)
    _SEASON_MAP_CACHE[int(season)] = (now, out)
    return out


def team_for_week(sleeper_id: str, season: int, week: int) -> Optional[str]:
    """The team a player was on in a specific season/week, or None if unknown.

    Prefers the per-week map (mid-season-trade accurate); falls back to the
    single per-season team from the history parquet.
    """
    sid = str(sleeper_id)
    wk_map = load_weekly_team_map(season).get(sid)
    if wk_map:
        team = wk_map.get(int(week))
        if team:
            return team
        # Player has weekly data for the season but not this week (bye / DNP):
        # fall through to the season team rather than guessing.
    return season_team_map(season).get(sid)


def teams_in_season(sleeper_id: str, season: int) -> List[Dict[str, object]]:
    """Every team a player appeared for in a season, with the weeks on each.

    Returns [{"team": "TB", "weeks": [1,2,...]}, ...] ordered by first appearance.
    From the per-week map when available (so a mid-season trade yields two
    entries); otherwise a single entry from the season team with weeks=[] (weeks
    unknown at season granularity). Empty list if the player has no history.
    """
    sid = str(sleeper_id)
    wk_map = load_weekly_team_map(season).get(sid)
    if wk_map:
        ordered: List[Dict[str, object]] = []
        seen: Dict[str, Dict[str, object]] = {}
        for wk in sorted(wk_map.keys()):
            team = wk_map[wk]
            entry = seen.get(team)
            if entry is None:
                entry = {"team": team, "weeks": []}
                seen[team] = entry
                ordered.append(entry)
            entry["weeks"].append(wk)  # type: ignore[union-attr]
        return ordered
    team = season_team_map(season).get(sid)
    return [{"team": team, "weeks": []}] if team else []


# ── Offline builder (cron only; needs network) ────────────────────────────────

def build_weekly_team_map(season: int) -> int:
    """Build cache/player_history/weekly_team_s{season}.json - the team each
    player was on each week. Returns the number of (player, week) entries
    written, 0 on failure. Network-dependent - invoked by cron, never at request
    time.

    Source: nfl_data_py.import_weekly_rosters (a per-week roster row per player,
    with the team he was on that week - handles mid-season trades). Preferred
    over import_weekly_data because the roster feed is published far earlier: for
    a just-completed season import_weekly_data 404s while weekly_rosters is
    already available. Falls back to import_weekly_data if rosters are missing.
    """
    try:
        import nfl_data_py as nfl  # optional dependency
    except Exception as e:
        logger.info("build_weekly_team_map: nfl_data_py unavailable (%s)", e)
        return 0

    df = None
    for _loader in ("import_weekly_rosters", "import_weekly_data"):
        fn = getattr(nfl, _loader, None)
        if fn is None:
            continue
        try:
            _d = fn([int(season)])
        except Exception as e:
            logger.info("build_weekly_team_map: %s(%s) failed (%s)", _loader, season, e)
            continue
        if _d is not None and not _d.empty:
            df = _d
            break
    if df is None or df.empty:
        return 0

    def _col(*names):
        for n in names:
            if n in df.columns:
                return n
        return None

    c_week = _col("week")
    c_team = _col("team", "recent_team")
    c_sleeper = _col("sleeper_id")            # roster feeds often carry it directly
    c_gsis = _col("player_id", "gsis_id")
    c_stype = _col("season_type", "game_type")
    if not (c_week and c_team and (c_sleeper or c_gsis)):
        logger.info("build_weekly_team_map: missing columns in %s", list(df.columns)[:12])
        return 0

    # Load the gsis->sleeper crosswalk whenever a gsis column exists, so rows
    # with a null sleeper_id (the roster feed leaves ~27% of them blank) can
    # still be resolved rather than silently dropped.
    crosswalk: Dict[str, str] = {}
    if c_gsis:
        try:
            from data_building.external_data.nflverse_metrics import _gsis_to_sleeper
            crosswalk = _gsis_to_sleeper() or {}
        except Exception as e:
            logger.info("build_weekly_team_map: id crosswalk unavailable (%s)", e)
    if not (c_sleeper or crosswalk):
        return 0

    def _norm_sleeper(v):
        if v is None:
            return None
        s = str(v).strip()
        if not s or s.lower() == "nan":
            return None
        try:
            return str(int(float(s)))  # sleeper ids often arrive as 4034.0
        except (ValueError, TypeError):
            return s

    out: Dict[str, Dict[str, str]] = {}
    count = 0
    for _, row in df.iterrows():
        if c_stype and str(row.get(c_stype) or "REG").upper() not in ("REG", "REG_SEASON", "REGULAR"):
            continue
        team = row.get(c_team)
        week = row.get(c_week)
        if team is None or week is None:
            continue
        # Prefer a direct sleeper_id; fall back to the gsis crosswalk per row
        # (sleeper_id is null on ~27% of roster rows).
        sid = _norm_sleeper(row.get(c_sleeper)) if c_sleeper else None
        if not sid and c_gsis and crosswalk:
            gsis = row.get(c_gsis)
            sid = crosswalk.get(str(gsis).strip()) if gsis is not None else None
        if not sid:
            continue
        try:
            wk = int(week)
        except (TypeError, ValueError):
            continue
        t = canon_team(team)
        if not t or t == "NAN":
            continue
        out.setdefault(sid, {})[str(wk)] = t
        count += 1

    if not count:
        return 0

    # Persist to the shared DB (the source of truth the web service reads) and
    # to the local file (fallback for DB-less environments).
    try:
        from dashboard_services.db import get_conn
        rows = [(sid, int(season), int(wk), t)
                for sid, wkmap in out.items() for wk, t in wkmap.items()]
        with get_conn() as conn:
            _init_week_team_table(conn)
            conn.execute("DELETE FROM player_week_team WHERE season = %s", (int(season),))
            with conn.cursor() as cur:
                cur.executemany(
                    "INSERT INTO player_week_team (player_id, season, week, team) "
                    "VALUES (%s, %s, %s, %s)",
                    rows,
                )
            conn.commit()
        logger.info("build_weekly_team_map: wrote %d rows to DB for %s", len(rows), season)
    except Exception:
        logger.debug("week-team DB write failed for %s", season, exc_info=True)

    try:
        _HISTORY_DIR.mkdir(parents=True, exist_ok=True)
        path = weekly_team_map_path(season)
        tmp = f"{path}.tmp"
        with open(tmp, "w") as f:
            json.dump(out, f, separators=(",", ":"))
        os.replace(tmp, path)
    except OSError:
        logger.debug("week-team file write failed for %s", season, exc_info=True)

    # Refresh the in-process cache so a same-process rebuild (the cron backfill
    # runs build_weekly_metrics right after) sees the new map immediately.
    _WEEKLY_MAP_CACHE.pop(int(season), None)
    logger.info("build_weekly_team_map: wrote %d player-weeks for %s", count, season)
    return count
