"""Compatibility shim: utils.utils is now split into domain modules.

All names that used to live here are re-exported from their new homes,
so existing `from utils.utils import X` imports keep working unchanged.
New code should import from the domain module directly (e.g. utils.data_cache).
"""

import requests  # noqa: F401  (re-exported: original utils.utils did `import requests`)

from utils.data_cache import (  # noqa: F401,F403
    CACHE_DIR,
    DATA_DIR,
    HEALTH_FILENAME,
    PLAYER_HISTORY_DIR,
    PLAYER_INVESTMENT_DIR,
    ROOT_DIR,
    STATUS_FINAL,
    STATUS_IN_PROGRESS,
    STATUS_NOT_STARTED,
    _JSON_CACHE,
    _JSON_CACHE_LOCK,
    _JSON_CACHE_MAX,
    _PLAYERS_INDEX_MERGED,
    _RELEVANT_INDEX_MERGED,
    _VALID_STATUSES,
    _WEEK_PROJ_BUILD_LOCK_TIMEOUT,
    _WEEK_PROJ_EMPTY_MAX_BYTES,
    _WEEK_PROJ_EMPTY_TTL_SEC,
    _WEEK_PROJ_FAIL_LOCK,
    _WEEK_PROJ_FAIL_UNTIL,
    _WEEK_PROJ_LOCKS,
    _WEEK_PROJ_LOCKS_GUARD,
    _WEEK_PROJ_MEMO,
    _WEEK_PROJ_MEMO_LOCK,
    _WEEK_PROJ_MEMO_MAX,
    _WEEK_PROJ_TTL_HOURS,
    _bye_lookup_for_overlay,
    _clear_func_cache_for_league,
    _overlay_players_index,
    _read_week_projection_file,
    _remove_empty_week_proj,
    _restore_week_proj_from_redis,
    _week_proj_cross_lock,
    _week_proj_file_is_empty,
    _week_proj_is_stale,
    _week_proj_lock,
    _week_proj_memo_max_from_env,
    clear_activity_cache_for_league,
    clear_league_provider_cache_for_league,
    clear_teams_cache_for_league,
    clear_weekly_cache_for_league,
    get_or_refresh_schedule_path,
    get_players_index_cached,
    get_week_projections_cached,
    get_week_schedule_cached,
    health_path,
    load_idp_index,
    load_model_value_table,
    load_players_index,
    load_relevant_index,
    load_teams_index,
    load_usage_table,
    load_week_projection,
    load_week_sched,
    load_week_schedule,
    load_week_stats,
    path_dynastyprocess_values,
    path_engine_table,
    path_fantasycalc_sf_values,
    path_fantasycalc_values,
    path_idp_index,
    path_model_value_table,
    path_players_index,
    path_relevant_index,
    path_teams_index,
    path_usage_table,
    path_week_proj,
    path_week_schedule,
    path_week_stats,
    read_health,
    read_json,
    read_json_cached,
    save_week_projections,
    save_week_schedule,
    write_json,
    write_step_health,
)

from utils.nfl import (  # noqa: F401,F403
    ALIASES,
    BASELINE_WEIGHTS,
    DST_CANON,
    EARLY_SEASON_CURRENT_WEIGHTS,
    EFF_LABELS,
    MIN_PARTICIPATION,
    POSITIONS,
    PROJECTION_DIVISOR,
    RANK_METRICS,
    REG_WEEKS,
    SCHED_TEAM_ALIAS,
    STADIUMS,
    STAT_KEYS,
    TEAM_ABBR_ALIASES,
    TEAM_ALIASES,
    TEAM_FULL_NAMES,
    VALID_PHASES,
    WINSOR_MULTIPLIER,
    _COLD_WEEK_START,
    _FULL_NAMES,
    _NFL_FRANCHISES,
    _NICKNAMES,
    _STAT_KEY_ALIASES,
    _as_float,
    _blank_pos_totals,
    _calendar_phase,
    _competition_ranks,
    _efficiency,
    _espn_logo_slug,
    _espn_logo_url,
    _per_game,
    _row_scores,
    _row_season_week,
    _safe_get,
    _stat_value,
    aggregate_completed_games,
    aggregate_defense_games,
    aggregate_defense_stats,
    aggregate_sleeper_team_weeks,
    aggregate_sleeper_team_weeks_for_teams,
    blend_value,
    build_defense_vs_position,
    build_offense_table,
    byes_for_season,
    calendar_nfl_season,
    canon_team,
    canonical_teams_index,
    canonicalize_game_teams,
    canonicalize_schedule,
    competition_ranks,
    completed_defense_games,
    compute_team_offense,
    current_sample_weight,
    def_team_logo_urls,
    fully_completed_weeks,
    game_adjustment,
    game_environment,
    get_bye_week,
    get_team_full_name,
    lookup_team_map,
    matchup_cell_ease,
    meaningful_participation,
    nfl_state_is_stale,
    nfl_state_last_good_at,
    norm_sched_team,
    normalize_nfl_state,
    normalize_nfl_team,
    normalize_schedule,
    normalize_team,
    pregame_baseline,
    rank_offense_table,
    rank_team_schedules,
    rank_values,
    ranked_metric,
    rating_cache_key,
    read_csv_team_totals,
    sched_rank_color,
    scoring_profile_hash,
    season_cache_key,
    season_weights,
    stadium_coords,
    table_fingerprint,
    team_abbr_keys,
)

from utils.projections import (  # noqa: F401,F403
    BASE,
    FULL_GAMES_MIN,
    FULL_VOLUME_MINS,
    NFL_TEAMS,
    POINTS,
    POINTS_PER_GAME,
    PROJECTION_CACHE_VERSION,
    ProjectionResult,
    QualificationPolicy,
    SCHEDULE_CACHE,
    SCHEDULE_TTL,
    SEASON_AVERAGE,
    TANK01_API_HOST,
    TANK01_API_KEY,
    TANK01_HOST,
    WEEKLY,
    _DEFAULT_MAX_PLAUSIBLE_PPG,
    _DEFAULT_RATES,
    _LOG,
    _MAX_PLAUSIBLE_PPG,
    _WEEK_STATS_TO_SLEEPER,
    _headers,
    _is_final,
    _is_regular,
    _positive,
    _rate,
    _season_total_projection,
    _sleeper_standard_points,
    _sleeper_stats_to_variants,
    _sleeper_week_value,
    _valid_ppg,
    brier_score,
    completed_points_summary,
    completed_regular_season_rounds,
    confidence_from_inputs,
    decision_regret,
    fetch_week_from_sleeper,
    fetch_week_from_tank01,
    fetch_week_projections,
    log_loss,
    map_weekly_projections_to_sleeper,
    pick_proj_variant,
    pick_proj_variant_from_draft_scoring,
    player_completed_weeks,
    player_qualification_note,
    player_sample_note,
    precision_at_k,
    projection_cache_key,
    projection_points,
    qualification_policy,
    rank_interval,
    resolve_projected_ppg,
    resolve_projected_ppg_many,
    scaled_minimum,
    score_stats,
    scoring_fingerprint,
    week_proj_map_from_bundles,
    week_stat_points,
    week_stats_line_points,
    weekly_projection_points,
)

from utils.game_status import (  # noqa: F401,F403
    BEFORE_WINDOW,
    IN_WINDOW,
    build_games_by_team,
    build_status_by_pid,
    build_status_for_week,
    build_teams_overview,
    decorate_player_display,
    finished_game_ids_for_week,
    game_has_started,
    get_league_rostered_player_ids,
    get_nfl_games_for_week,
    normalize_game_status_from_tank01,
    pinfo_for_pid,
    resolve_adv_metrics_completed_week,
    streak_class,
    streak_edge_class,
    week_has_final_game,
)

from utils.players import (  # noqa: F401,F403
    BLEND_FULL_SEASON,
    PUNCT_RE,
    PlayerIdentityResolver,
    SUFFIXES,
    WS_RE,
    _BOX_PAYLOAD_CACHE,
    _BOX_PAYLOAD_TTL_FINAL,
    _BOX_PAYLOAD_TTL_LIVE,
    _BOX_PAYLOAD_TTL_SCHEDULED,
    _DEFAULT_THRESHOLDS,
    _ID_FIELDS,
    _MIN_GAMES,
    _POST_WEEK_LABELS,
    _POS_ORDER,
    _POS_THRESHOLDS,
    _ROLE_POSITIONS,
    _TEAM_ABBR_ALIASES,
    _TEAM_CANON,
    _TEAM_SCHEDULE_CACHE,
    _TEAM_SCHEDULE_TTL,
    _VERIFIED_GIVEN_ALIASES,
    _block_num,
    _bye_row,
    _canon,
    _cell_value,
    _enrich_from_scores,
    _fmt_date_label,
    _fmt_kickoff,
    _group_columns,
    _has_any,
    _label_for,
    _logo_for,
    _lookup_team_map,
    _percentile,
    _player_identity,
    _result_for_team,
    _row_from_game,
    _safe_float,
    _stat_bundle,
    _status_from_game,
    _team_keys,
    _teams_match,
    blended_consistency_profile,
    build_team_schedule,
    consistency_profile,
    from_players_map,
    get_shaped_boxscore,
    logger,
    norm_name,
    normalize_name,
    normalize_player_name,
    resolve_player_identity,
    resolve_team_for_season,
    safe_owner_name,
    shape_boxscore_payload,
    tank_boxscore_game_id,
)

from utils.live_stats import (  # noqa: F401,F403
    _normalize_dst_stats,
    _normalize_qb_stats,
    _normalize_skill_stats,
    _safe_int,
    box_score_line_is_trusted,
    build_and_save_week_stats_for_league,
    build_live_stats_for_game_from_tank,
    build_tank_player_index,
    count_roster_positions,
    get_live_game_ids_for_today,
    get_started_game_ids_for_week,
    load_sleeper_week_stats,
    merge_live_stats_into_league_week_stats,
    overlay_idp_and_k_stats_from_sleeper,
    parse_position_table_for_week,
    parse_stat_lines_for_pos,
    parse_team_week_pos_player_stats,
    player_week_stat_entry,
    sleeper_week_stats_path,
    tank01_status_confirms_started,
)

from utils.draft import (  # noqa: F401,F403
    DR_CONSTRUCTION_REDRAFT,
    DR_CONSTRUCTION_STARTUP,
    DR_SPLIT_REDRAFT,
    DR_SPLIT_STARTUP,
    KEEP,
    KeeperCandidate,
    KeeperRules,
    PASS,
    PS_AGE_PEAKS,
    PS_WEIGHTS,
    TOSS,
    _FLEX_COVERS,
    _has_flex_for,
    _optimize_unique_rounds,
    _sort_key,
    adjust_adp_for_keepers,
    analyze,
    avg_pick_value_for_round,
    bucket_for_slot,
    clamp01,
    compute_pick_score,
    compute_pick_slots,
    cost_collisions,
    dr_apply_field_curve,
    dr_avg_top_n,
    dr_construction_mix,
    dr_grade_letter,
    dr_grade_split,
    dr_league_lineup_avg,
    dr_letter_to_score,
    dr_lineup_score,
    dr_optimal_lineup,
    dr_peer_starter_avg,
    dr_peer_value_ps,
    dr_resolve_strength_baseline,
    dr_rookie_team_score,
    dr_slot_eligible,
    dr_starter_metric_avg,
    dr_team_grade_score,
    dr_weighted_pick_score,
    empirical_slot_allocation,
    evaluate,
    is_pick_asset_id,
    keeper_cost_round,
    keeper_surplus_value,
    market_round,
    parse_pick_asset,
    pick_label,
    pick_value,
    pick_value_from_table,
    placements_from_bracket,
    project_league_keepers,
    ps_tier_of,
    resolve_cost_collisions,
    slots_from_regular_season,
    starter_counts,
    total_surplus,
    verdict,
)

from utils.core import (  # noqa: F401,F403
    BETTER_OUTWARD_METRICS,
    BETTER_OUTWARD_SIGNS,
    EASTERN,
    _COMMENT_RE,
    _LITERAL_BLOCK_RE,
    _MISSING,
    api_int,
    api_str,
    ord_suffix,
    ordinal,
    rel_time,
    safe_float,
    safe_int,
    safe_int_or_none,
    safe_local_url,
    sanitize_for_json,
    strip_html_comments,
    validate_league_id,
    z_better_outward,
)

from bs4 import (  # noqa: F401,F403
    BeautifulSoup,
)


from collections import (  # noqa: F401,F403
    OrderedDict as _OrderedDict,
    defaultdict,
)


from contextlib import (  # noqa: F401,F403
    contextmanager as _contextmanager,
)


from dashboard_services.api import (  # noqa: F401,F403
    _fetch_league,
    fetch_tank_boxscore,
    fetch_team_game_logs_html,
    get_matchups,
    get_nfl_games_for_week_raw,
    get_nfl_players,
    get_nfl_state,
    get_rosters,
    get_traded_picks,
    get_transactions,
    get_users,
)


from dashboard_services.display_names import (  # noqa: F401,F403
    team_label_from_user,
    username_from_user,
)


from datetime import (  # noqa: F401,F403
    date,
    datetime,
    timezone,
)


from pathlib import (  # noqa: F401,F403
    Path,
)


from typing import (  # noqa: F401,F403
    Any,
    Callable,
    Dict,
    Iterable,
    List,
    Optional,
    TYPE_CHECKING,
)


__all__ = ['ALIASES', 'Any', 'BASE', 'BASELINE_WEIGHTS', 'BEFORE_WINDOW', 'BETTER_OUTWARD_METRICS', 'BETTER_OUTWARD_SIGNS', 'BLEND_FULL_SEASON', 'BeautifulSoup', 'CACHE_DIR', 'Callable', 'DATA_DIR', 'DR_CONSTRUCTION_REDRAFT', 'DR_CONSTRUCTION_STARTUP', 'DR_SPLIT_REDRAFT', 'DR_SPLIT_STARTUP', 'DST_CANON', 'Dict', 'EARLY_SEASON_CURRENT_WEIGHTS', 'EASTERN', 'EFF_LABELS', 'FULL_GAMES_MIN', 'FULL_VOLUME_MINS', 'HEALTH_FILENAME', 'IN_WINDOW', 'Iterable', 'KEEP', 'KeeperCandidate', 'KeeperRules', 'List', 'MIN_PARTICIPATION', 'NFL_TEAMS', 'Optional', 'PASS', 'PLAYER_HISTORY_DIR', 'PLAYER_INVESTMENT_DIR', 'POINTS', 'POINTS_PER_GAME', 'POSITIONS', 'PROJECTION_CACHE_VERSION', 'PROJECTION_DIVISOR', 'PS_AGE_PEAKS', 'PS_WEIGHTS', 'PUNCT_RE', 'Path', 'PlayerIdentityResolver', 'ProjectionResult', 'QualificationPolicy', 'RANK_METRICS', 'REG_WEEKS', 'ROOT_DIR', 'SCHEDULE_CACHE', 'SCHEDULE_TTL', 'SCHED_TEAM_ALIAS', 'SEASON_AVERAGE', 'STADIUMS', 'STATUS_FINAL', 'STATUS_IN_PROGRESS', 'STATUS_NOT_STARTED', 'STAT_KEYS', 'SUFFIXES', 'TANK01_API_HOST', 'TANK01_API_KEY', 'TANK01_HOST', 'TEAM_ABBR_ALIASES', 'TEAM_ALIASES', 'TEAM_FULL_NAMES', 'TOSS', 'TYPE_CHECKING', 'VALID_PHASES', 'WEEKLY', 'WINSOR_MULTIPLIER', 'WS_RE', '_BOX_PAYLOAD_CACHE', '_BOX_PAYLOAD_TTL_FINAL', '_BOX_PAYLOAD_TTL_LIVE', '_BOX_PAYLOAD_TTL_SCHEDULED', '_COLD_WEEK_START', '_COMMENT_RE', '_DEFAULT_MAX_PLAUSIBLE_PPG', '_DEFAULT_RATES', '_DEFAULT_THRESHOLDS', '_FLEX_COVERS', '_FULL_NAMES', '_ID_FIELDS', '_JSON_CACHE', '_JSON_CACHE_LOCK', '_JSON_CACHE_MAX', '_LITERAL_BLOCK_RE', '_LOG', '_MAX_PLAUSIBLE_PPG', '_MIN_GAMES', '_MISSING', '_NFL_FRANCHISES', '_NICKNAMES', '_OrderedDict', '_PLAYERS_INDEX_MERGED', '_POST_WEEK_LABELS', '_POS_ORDER', '_POS_THRESHOLDS', '_RELEVANT_INDEX_MERGED', '_ROLE_POSITIONS', '_STAT_KEY_ALIASES', '_TEAM_ABBR_ALIASES', '_TEAM_CANON', '_TEAM_SCHEDULE_CACHE', '_TEAM_SCHEDULE_TTL', '_VALID_STATUSES', '_VERIFIED_GIVEN_ALIASES', '_WEEK_PROJ_BUILD_LOCK_TIMEOUT', '_WEEK_PROJ_EMPTY_MAX_BYTES', '_WEEK_PROJ_EMPTY_TTL_SEC', '_WEEK_PROJ_FAIL_LOCK', '_WEEK_PROJ_FAIL_UNTIL', '_WEEK_PROJ_LOCKS', '_WEEK_PROJ_LOCKS_GUARD', '_WEEK_PROJ_MEMO', '_WEEK_PROJ_MEMO_LOCK', '_WEEK_PROJ_MEMO_MAX', '_WEEK_PROJ_TTL_HOURS', '_WEEK_STATS_TO_SLEEPER', '_as_float', '_blank_pos_totals', '_block_num', '_bye_lookup_for_overlay', '_bye_row', '_calendar_phase', '_canon', '_cell_value', '_clear_func_cache_for_league', '_competition_ranks', '_contextmanager', '_efficiency', '_enrich_from_scores', '_espn_logo_slug', '_espn_logo_url', '_fetch_league', '_fmt_date_label', '_fmt_kickoff', '_group_columns', '_has_any', '_has_flex_for', '_headers', '_is_final', '_is_regular', '_label_for', '_logo_for', '_lookup_team_map', '_normalize_dst_stats', '_normalize_qb_stats', '_normalize_skill_stats', '_optimize_unique_rounds', '_overlay_players_index', '_per_game', '_percentile', '_player_identity', '_positive', '_rate', '_read_week_projection_file', '_remove_empty_week_proj', '_restore_week_proj_from_redis', '_result_for_team', '_row_from_game', '_row_scores', '_row_season_week', '_safe_float', '_safe_get', '_safe_int', '_season_total_projection', '_sleeper_standard_points', '_sleeper_stats_to_variants', '_sleeper_week_value', '_sort_key', '_stat_bundle', '_stat_value', '_status_from_game', '_team_keys', '_teams_match', '_valid_ppg', '_week_proj_cross_lock', '_week_proj_file_is_empty', '_week_proj_is_stale', '_week_proj_lock', '_week_proj_memo_max_from_env', 'adjust_adp_for_keepers', 'aggregate_completed_games', 'aggregate_defense_games', 'aggregate_defense_stats', 'aggregate_sleeper_team_weeks', 'aggregate_sleeper_team_weeks_for_teams', 'analyze', 'api_int', 'api_str', 'avg_pick_value_for_round', 'blend_value', 'blended_consistency_profile', 'box_score_line_is_trusted', 'brier_score', 'bucket_for_slot', 'build_and_save_week_stats_for_league', 'build_defense_vs_position', 'build_games_by_team', 'build_live_stats_for_game_from_tank', 'build_offense_table', 'build_status_by_pid', 'build_status_for_week', 'build_tank_player_index', 'build_team_schedule', 'build_teams_overview', 'byes_for_season', 'calendar_nfl_season', 'canon_team', 'canonical_teams_index', 'canonicalize_game_teams', 'canonicalize_schedule', 'clamp01', 'clear_activity_cache_for_league', 'clear_league_provider_cache_for_league', 'clear_teams_cache_for_league', 'clear_weekly_cache_for_league', 'competition_ranks', 'completed_defense_games', 'completed_points_summary', 'completed_regular_season_rounds', 'compute_pick_score', 'compute_pick_slots', 'compute_team_offense', 'confidence_from_inputs', 'consistency_profile', 'cost_collisions', 'count_roster_positions', 'current_sample_weight', 'date', 'datetime', 'decision_regret', 'decorate_player_display', 'def_team_logo_urls', 'defaultdict', 'dr_apply_field_curve', 'dr_avg_top_n', 'dr_construction_mix', 'dr_grade_letter', 'dr_grade_split', 'dr_league_lineup_avg', 'dr_letter_to_score', 'dr_lineup_score', 'dr_optimal_lineup', 'dr_peer_starter_avg', 'dr_peer_value_ps', 'dr_resolve_strength_baseline', 'dr_rookie_team_score', 'dr_slot_eligible', 'dr_starter_metric_avg', 'dr_team_grade_score', 'dr_weighted_pick_score', 'empirical_slot_allocation', 'evaluate', 'fetch_tank_boxscore', 'fetch_team_game_logs_html', 'fetch_week_from_sleeper', 'fetch_week_from_tank01', 'fetch_week_projections', 'finished_game_ids_for_week', 'from_players_map', 'fully_completed_weeks', 'game_adjustment', 'game_environment', 'game_has_started', 'get_bye_week', 'get_league_rostered_player_ids', 'get_live_game_ids_for_today', 'get_matchups', 'get_nfl_games_for_week', 'get_nfl_games_for_week_raw', 'get_nfl_players', 'get_nfl_state', 'get_or_refresh_schedule_path', 'get_players_index_cached', 'get_rosters', 'get_shaped_boxscore', 'get_started_game_ids_for_week', 'get_team_full_name', 'get_traded_picks', 'get_transactions', 'get_users', 'get_week_projections_cached', 'get_week_schedule_cached', 'health_path', 'is_pick_asset_id', 'keeper_cost_round', 'keeper_surplus_value', 'load_idp_index', 'load_model_value_table', 'load_players_index', 'load_relevant_index', 'load_sleeper_week_stats', 'load_teams_index', 'load_usage_table', 'load_week_projection', 'load_week_sched', 'load_week_schedule', 'load_week_stats', 'log_loss', 'logger', 'lookup_team_map', 'map_weekly_projections_to_sleeper', 'market_round', 'matchup_cell_ease', 'meaningful_participation', 'merge_live_stats_into_league_week_stats', 'nfl_state_is_stale', 'nfl_state_last_good_at', 'norm_name', 'norm_sched_team', 'normalize_game_status_from_tank01', 'normalize_name', 'normalize_nfl_state', 'normalize_nfl_team', 'normalize_player_name', 'normalize_schedule', 'normalize_team', 'ord_suffix', 'ordinal', 'overlay_idp_and_k_stats_from_sleeper', 'parse_pick_asset', 'parse_position_table_for_week', 'parse_stat_lines_for_pos', 'parse_team_week_pos_player_stats', 'path_dynastyprocess_values', 'path_engine_table', 'path_fantasycalc_sf_values', 'path_fantasycalc_values', 'path_idp_index', 'path_model_value_table', 'path_players_index', 'path_relevant_index', 'path_teams_index', 'path_usage_table', 'path_week_proj', 'path_week_schedule', 'path_week_stats', 'pick_label', 'pick_proj_variant', 'pick_proj_variant_from_draft_scoring', 'pick_value', 'pick_value_from_table', 'pinfo_for_pid', 'placements_from_bracket', 'player_completed_weeks', 'player_qualification_note', 'player_sample_note', 'player_week_stat_entry', 'precision_at_k', 'pregame_baseline', 'project_league_keepers', 'projection_cache_key', 'projection_points', 'ps_tier_of', 'qualification_policy', 'rank_interval', 'rank_offense_table', 'rank_team_schedules', 'rank_values', 'ranked_metric', 'rating_cache_key', 'read_csv_team_totals', 'read_health', 'read_json', 'read_json_cached', 'rel_time', 'requests', 'resolve_adv_metrics_completed_week', 'resolve_cost_collisions', 'resolve_player_identity', 'resolve_projected_ppg', 'resolve_projected_ppg_many', 'resolve_team_for_season', 'safe_float', 'safe_int', 'safe_int_or_none', 'safe_local_url', 'safe_owner_name', 'sanitize_for_json', 'save_week_projections', 'save_week_schedule', 'scaled_minimum', 'sched_rank_color', 'score_stats', 'scoring_fingerprint', 'scoring_profile_hash', 'season_cache_key', 'season_weights', 'shape_boxscore_payload', 'sleeper_week_stats_path', 'slots_from_regular_season', 'stadium_coords', 'starter_counts', 'streak_class', 'streak_edge_class', 'strip_html_comments', 'table_fingerprint', 'tank01_status_confirms_started', 'tank_boxscore_game_id', 'team_abbr_keys', 'team_label_from_user', 'timezone', 'total_surplus', 'username_from_user', 'validate_league_id', 'verdict', 'week_has_final_game', 'week_proj_map_from_bundles', 'week_stat_points', 'week_stats_line_points', 'weekly_projection_points', 'write_json', 'write_step_health', 'z_better_outward']


# --- monkeypatch propagation (see utils/_shim.py) ---
from utils._shim import propagate_sets_to as _propagate_sets_to
import importlib as _importlib
_propagate_sets_to(__name__, _importlib.import_module("utils.data_cache"), _importlib.import_module("utils.nfl"), _importlib.import_module("utils.projections"), _importlib.import_module("utils.game_status"), _importlib.import_module("utils.players"), _importlib.import_module("utils.live_stats"), _importlib.import_module("utils.draft"), _importlib.import_module("utils.core"))
