from __future__ import annotations

import html
import json
import logging

import pandas as pd

from dashboard_services.ai.cache import AI_CACHE_DIR, save_cached_ai_text
from dashboard_services.ai.client import (
    AIRateLimitError,
    AIUnavailableError,
    clean_ai_text,
    get_ai_client,
)
from dashboard_services.ai.renderer import ai_available

logger = logging.getLogger(__name__)

# Sentinel that joins the recap column and the game-of-the-week card in a single
# cache entry (they're generated by one AI call). Chosen so it can never appear
# in rendered HTML.
_NEXT_WEEK_SPLIT = "<!--__NEXT_WEEK_CARD__-->"


def _load_recap_no_ttl(cache_key: str) -> str | None:
    """Load a cached weekly recap without applying the global TTL.
    The cache key includes the league/season/week, so once a week's
    recap is written it remains valid until that week regenerates."""
    path = AI_CACHE_DIR / f"{cache_key}.json"
    if not path.exists():
        return None
    try:
        obj = json.loads(path.read_text(encoding="utf-8"))
        return obj.get("content")
    except Exception:
        return None


def _streak_for(results: list[str]) -> str:
    """Compute current streak like 'W3' or 'L2' from a list of 'W'/'L' results."""
    if not results:
        return "-"
    last = results[-1]
    n = 1
    for r in reversed(results[:-1]):
        if r == last:
            n += 1
        else:
            break
    return f"{last}{n}"


def _build_team_storylines(
        df_weekly: pd.DataFrame,
        selected_week: int,
        team_by_rid: dict,
) -> list[dict]:
    """For each team, compute record/rank/streak before and after the selected week."""
    fin_df = df_weekly[(df_weekly["finalized"] == True) & (df_weekly["week"] <= selected_week)].copy()
    if fin_df.empty:
        return []

    fin_df["win"] = fin_df["points"] > fin_df["points_against"]

    # Build per-team history sorted by week
    teams: dict[str, dict] = {}
    for rid, grp in fin_df.groupby("roster_id"):
        grp = grp.sort_values("week")
        results = ["W" if w else "L" for w in grp["win"].tolist()]
        # Snapshot through selected_week
        owner = str(grp["owner"].iloc[0])
        teams[str(rid)] = {
            "rid": str(rid),
            "team": team_by_rid.get(str(rid), owner),
            "owner": owner,
            "results": results,
            "weeks": [int(w) for w in grp["week"].tolist()],
            "pts_by_week": [float(p) for p in grp["points"].tolist()],
        }

    # Compute snapshots BEFORE selected_week
    snap_before: dict[str, dict] = {}
    snap_after: dict[str, dict] = {}
    for rid, t in teams.items():
        # Before this week: only weeks < selected_week
        before_idx = [i for i, w in enumerate(t["weeks"]) if w < selected_week]
        wins_b = sum(1 for i in before_idx if t["results"][i] == "W")
        losses_b = sum(1 for i in before_idx if t["results"][i] == "L")
        pf_b = sum(t["pts_by_week"][i] for i in before_idx)
        snap_before[rid] = {
            "wins": wins_b, "losses": losses_b, "pf": pf_b,
            "streak": _streak_for([t["results"][i] for i in before_idx]),
        }
        # After (through this week, inclusive)
        wins_a = sum(1 for r in t["results"] if r == "W")
        losses_a = sum(1 for r in t["results"] if r == "L")
        pf_a = sum(t["pts_by_week"])
        snap_after[rid] = {
            "wins": wins_a, "losses": losses_a, "pf": pf_a,
            "streak": _streak_for(t["results"]),
        }

    # Compute rank (1 = best) by wins then PF
    def _rank(snap_map):
        items = list(snap_map.items())
        items.sort(key=lambda x: (-x[1]["wins"], -x[1]["pf"]))
        return {rid: i + 1 for i, (rid, _s) in enumerate(items)}

    rank_before = _rank(snap_before)
    rank_after = _rank(snap_after)

    # This-week result per team
    week_df = df_weekly[(df_weekly["week"] == selected_week) & (df_weekly["finalized"] == True)]
    week_result_by_rid: dict[str, dict] = {}
    for _, row in week_df.iterrows():
        rid = str(row.get("roster_id"))
        week_result_by_rid[rid] = {
            "pts": float(row.get("points") or 0),
            "opp_pts": float(row.get("points_against") or 0),
            "won": bool(row.get("points", 0) > row.get("points_against", 0)),
        }

    storylines = []
    for rid, t in teams.items():
        wr = week_result_by_rid.get(rid, {})
        before = snap_before[rid]
        after = snap_after[rid]

        season_weeks = [
            {
                "week": t["weeks"][i],
                "result": t["results"][i],
                "pts": round(t["pts_by_week"][i], 1),
            }
            for i in range(len(t["weeks"]))
        ]

        storylines.append({
            "rid": rid,
            "team": t["team"],
            "owner": t["owner"],
            "this_week_pts": wr.get("pts"),
            "opp_pts": wr.get("opp_pts"),
            "won_this_week": wr.get("won"),
            "record_before": f"{before['wins']}-{before['losses']}",
            "record_after": f"{after['wins']}-{after['losses']}",
            "rank_before": rank_before.get(rid),
            "rank_after": rank_after.get(rid),
            "rank_change": (rank_before.get(rid) or 0) - (rank_after.get(rid) or 0),  # +ve = moved up
            "streak": after["streak"],
            "streak_before": before["streak"],
            "pf_after": round(after["pf"], 1),
            "season_weeks": season_weeks,
        })

    storylines.sort(key=lambda x: x["rank_after"] or 99)
    return storylines


def _build_matchup_context(
        df_weekly: pd.DataFrame,
        selected_week: int,
        team_by_rid: dict,
) -> list[dict]:
    """For each matchup this week, compute h2h record and prior meetings this season."""
    fin_df = df_weekly[df_weekly["finalized"] == True].copy()
    if fin_df.empty:
        return []

    # (week, matchup_id) -> [(rid, pts)]
    pairs: dict[tuple, list] = {}
    for _, row in fin_df.iterrows():
        key = (int(row["week"]), int(row.get("matchup_id") or 0))
        pairs.setdefault(key, []).append((str(row["roster_id"]), float(row["points"])))

    this_week = {k: v for k, v in pairs.items() if k[0] == selected_week and len(v) == 2}

    result = []
    for (_w, _mid), sides in this_week.items():
        rid_a, pts_a = sides[0]
        rid_b, pts_b = sides[1]
        team_a = team_by_rid.get(rid_a, rid_a)
        team_b = team_by_rid.get(rid_b, rid_b)

        prior = []
        for (w, _m), s in pairs.items():
            if w >= selected_week or len(s) != 2:
                continue
            if {s[0][0], s[1][0]} == {rid_a, rid_b}:
                a_side = next(x for x in s if x[0] == rid_a)
                b_side = next(x for x in s if x[0] == rid_b)
                prior.append({
                    "week": w,
                    "a_pts": round(a_side[1], 1),
                    "b_pts": round(b_side[1], 1),
                    "winner": team_a if a_side[1] > b_side[1] else team_b,
                })

        prior.sort(key=lambda x: x["week"])
        a_wins = sum(1 for p in prior if p["winner"] == team_a)
        b_wins = sum(1 for p in prior if p["winner"] == team_b)

        entry: dict = {
            "team_a": team_a,
            "team_b": team_b,
            "team_a_pts": round(pts_a, 1),
            "team_b_pts": round(pts_b, 1),
            "winner": team_a if pts_a > pts_b else team_b,
        }
        if prior:
            entry["h2h"] = {
                "team_a_wins": a_wins,
                "team_b_wins": b_wins,
                "prior_meetings": prior,
            }
        result.append(entry)

    return result


# Injury statuses that keep a player out (or likely out) of a lineup. A
# QUESTIONABLE tag is deliberately excluded — those players usually suit up, so
# flagging them as "missing" would cry wolf.
_OUT_STATUSES = {"OUT", "IR", "DOUBTFUL", "PUP", "NFI", "SUSP"}


def _prior_series(
        df_weekly: pd.DataFrame,
        rid_a: str,
        rid_b: str,
        upto_week: int,
) -> tuple[int, int, int]:
    """Season head-to-head between two rosters through ``upto_week`` (inclusive):
    (meetings, rid_a wins, rid_b wins)."""
    fin = df_weekly[(df_weekly["finalized"] == True) & (df_weekly["week"] <= upto_week)]
    meetings = a_wins = b_wins = 0
    for (_w, _mid), g in fin.groupby(["week", "matchup_id"]):
        if len(g) != 2:
            continue
        rids = [str(r) for r in g["roster_id"].tolist()]
        if str(rid_a) not in rids or str(rid_b) not in rids:
            continue
        ga = g[g["roster_id"].astype(str) == str(rid_a)].iloc[0]
        gb = g[g["roster_id"].astype(str) == str(rid_b)].iloc[0]
        meetings += 1
        if float(ga["points"]) > float(gb["points"]):
            a_wins += 1
        elif float(gb["points"]) > float(ga["points"]):
            b_wins += 1
    return meetings, a_wins, b_wins


def _injured_starters(team_block: dict, player_index: dict, value_by_pid: dict) -> list[dict]:
    """Starters on a team's projected next-week lineup who are OUT/IR/etc.,
    ordered by dynasty value so the biggest name leads."""
    out: list[dict] = []
    for p in (team_block.get("starters") or []):
        pid = str(p.get("pid") or "")
        info = player_index.get(pid) or {}
        raw = str(info.get("injury_status") or info.get("status") or "").strip().upper()
        if raw in _OUT_STATUSES:
            out.append({
                "name": p.get("name"),
                "pos": p.get("pos"),
                "status": raw,
                "value": value_by_pid.get(pid, 0.0),
            })
    out.sort(key=lambda x: x["value"] or 0.0, reverse=True)
    return out


def _build_next_week_preview(
        df_weekly: pd.DataFrame,
        next_week_matchups: list,
        storyline_by_rid: dict,
        player_index: dict,
        value_by_pid: dict,
        selected_week: int,
        playoff_start: int,
        playoff_teams: int,
        num_teams: int,
) -> dict | None:
    """Score each of next week's matchups on marquee value, closeness, playoff
    stakes, streaks, a rematch angle, and missing starters, then pick a game of
    the week. Everything here is deterministic and grounded in real data — the AI
    only narrates the pick, it doesn't choose it."""
    if not next_week_matchups:
        return None

    next_week = selected_week + 1
    # Regular-season games left after next week's slate (0 = next week is the finale).
    weeks_left_after = max(0, playoff_start - 1 - next_week)

    games: list[dict] = []
    for m in next_week_matchups:
        left = m.get("left") or {}
        right = m.get("right") or {}
        rid_a = str(left.get("roster_id") or "")
        rid_b = str(right.get("roster_id") or "")
        sa = storyline_by_rid.get(rid_a)
        sb = storyline_by_rid.get(rid_b)
        if not sa or not sb:
            continue

        rank_a = sa["rank_after"] or num_teams
        rank_b = sb["rank_after"] or num_teams
        avg_rank = (rank_a + rank_b) / 2.0
        rank_gap = abs(rank_a - rank_b)

        inj_a = _injured_starters(left, player_index, value_by_pid)
        inj_b = _injured_starters(right, player_index, value_by_pid)
        meetings, a_wins, b_wins = _prior_series(df_weekly, rid_a, rid_b, selected_week)

        reasons: list[str] = []

        # Marquee: two good teams playing (lower average rank = better).
        score = (num_teams - avg_rank) * 2.0
        if avg_rank <= max(2, num_teams * 0.3):
            reasons.append("two of the league's best")

        # Closeness in the standings.
        score += max(0.0, 4 - rank_gap)
        if rank_gap <= 1:
            reasons.append("neighbors in the standings")

        # Hot streaks on either side.
        for s in (sa, sb):
            st = str(s.get("streak") or "")
            if st.startswith("W") and int(st[1:] or 0) >= 3:
                score += min(int(st[1:] or 0), 5) * 0.6
                reasons.append(f"{s['team']} on a {st} run")

        # Playoff stakes: teams sitting on the bubble as the field tightens.
        near_cut = sum(1 for s in (sa, sb) if abs((s["rank_after"] or num_teams) - playoff_teams) <= 1)
        if playoff_teams and weeks_left_after <= 4 and near_cut:
            score += near_cut * (5 - weeks_left_after)
            reasons.append("playoff-race implications")

        # Rematch / season series.
        if meetings >= 1:
            score += 1.5
            reasons.append("a rematch" if meetings == 1 else "the rubber match")

        # Missing starters add intrigue (and are the story either way).
        if inj_a or inj_b:
            top_inj = max(inj_a + inj_b, key=lambda x: x["value"] or 0.0)
            score += 1.0
            reasons.append(f"{top_inj['name']} ({top_inj['status']}) in question")

        games.append({
            "team_a": sa["team"], "team_b": sb["team"],
            "record_a": sa["record_after"], "record_b": sb["record_after"],
            "rank_a": rank_a, "rank_b": rank_b,
            "streak_a": sa.get("streak"), "streak_b": sb.get("streak"),
            "h2h": {"meetings": meetings, "a_wins": a_wins, "b_wins": b_wins} if meetings else None,
            "injured_a": inj_a, "injured_b": inj_b,
            "reasons": reasons,
            "score": round(score, 2),
        })

    if not games:
        return None

    games.sort(key=lambda g: -g["score"])
    return {
        "next_week": next_week,
        "weeks_left_after": weeks_left_after,
        "game_of_the_week": games[0],
        "also_watch": [
            {"team_a": g["team_a"], "team_b": g["team_b"], "reasons": g["reasons"][:2]}
            for g in games[1:3]
        ],
    }


def build_weekly_recap_payload(
        df_weekly: pd.DataFrame,
        matchups_by_week: dict,
        selected_week: int,
        team_by_rid: dict,
        league: dict,
        next_week_matchups: list | None = None,
        player_index: dict | None = None,
        value_by_pid: dict | None = None,
) -> dict:
    storylines = _build_team_storylines(df_weekly, selected_week, team_by_rid)
    matchup_context = _build_matchup_context(df_weekly, selected_week, team_by_rid)

    settings = (league or {}).get("settings") or {}
    playoff_start = int(settings.get("playoff_week_start") or 14)
    playoff_teams = int(settings.get("playoff_teams") or 6)
    league_name = (league or {}).get("name") or "the league"

    weeks_until_playoffs = max(0, playoff_start - 1 - selected_week)

    # Identify upsets (lower-ranked-before beats higher-ranked-before)
    week_matchups_raw = matchups_by_week.get(selected_week) or []
    upsets = []
    biggest_blowout = None
    for m in week_matchups_raw:
        l = m.get("left") or {}
        r = m.get("right") or {}
        l_rid = str(l.get("roster_id") or "")
        r_rid = str(r.get("roster_id") or "")
        l_pts = float(l.get("pts_total") or 0)
        r_pts = float(r.get("pts_total") or 0)
        if l_pts == r_pts:
            continue
        winner_rid, loser_rid = (l_rid, r_rid) if l_pts > r_pts else (r_rid, l_rid)
        winner_pts, loser_pts = (l_pts, r_pts) if l_pts > r_pts else (r_pts, l_pts)
        winner = next((s for s in storylines if s["team"] == team_by_rid.get(winner_rid)
                       or s["owner"] == (l.get("username") if winner_rid == l_rid else r.get("username"))), None)
        loser = next((s for s in storylines if s["team"] == team_by_rid.get(loser_rid)
                      or s["owner"] == (l.get("username") if loser_rid == l_rid else r.get("username"))), None)
        margin = winner_pts - loser_pts
        if winner and loser and winner["rank_before"] and loser["rank_before"]:
            if winner["rank_before"] > loser["rank_before"] + 2:
                upsets.append({
                    "winner": winner["team"], "loser": loser["team"],
                    "winner_rank_before": winner["rank_before"],
                    "loser_rank_before": loser["rank_before"],
                    "margin": round(margin, 1),
                })
        if biggest_blowout is None or margin > biggest_blowout["margin"]:
            biggest_blowout = {
                "winner": team_by_rid.get(winner_rid, "Unknown"),
                "loser": team_by_rid.get(loser_rid, "Unknown"),
                "winner_pts": round(winner_pts, 1),
                "loser_pts": round(loser_pts, 1),
                "margin": round(margin, 1),
            }

    # Playoff race tightness: gap between cutline team and just-outside team
    playoff_race = None
    if storylines and playoff_teams and len(storylines) > playoff_teams:
        cutline = storylines[playoff_teams - 1]
        bubble = storylines[playoff_teams]
        wins_gap = (cutline["record_after"].split("-")[0] != bubble["record_after"].split("-")[0])
        playoff_race = {
            "cutline_team": cutline["team"],
            "cutline_record": cutline["record_after"],
            "bubble_team": bubble["team"],
            "bubble_record": bubble["record_after"],
            "tight": not wins_gap,
        }

    # Notable highlights
    high_scorer = max(storylines, key=lambda x: x["this_week_pts"] or 0) if storylines else None
    low_scorer = min(storylines, key=lambda x: x["this_week_pts"] if x["this_week_pts"] is not None else 1e9) if storylines else None
    hot_streaks = [s for s in storylines if s["streak"].startswith("W") and int(s["streak"][1:] or 0) >= 3]
    cold_streaks = [s for s in storylines if s["streak"].startswith("L") and int(s["streak"][1:] or 0) >= 2]
    big_movers = sorted([s for s in storylines if abs(s["rank_change"]) >= 2],
                        key=lambda x: -abs(x["rank_change"]))[:3]

    num_teams = len(storylines)
    storyline_by_rid = {str(s["rid"]): s for s in storylines}
    next_week_preview = _build_next_week_preview(
        df_weekly,
        next_week_matchups or [],
        storyline_by_rid,
        player_index or {},
        value_by_pid or {},
        selected_week,
        playoff_start,
        playoff_teams,
        num_teams,
    )

    return {
        "league_name": league_name,
        "week": selected_week,
        "weeks_until_playoffs": weeks_until_playoffs,
        "playoff_teams": playoff_teams,
        "teams": [
            {
                "team": s["team"],
                "rank_before": s["rank_before"],
                "rank_after": s["rank_after"],
                "record_after": s["record_after"],
                "streak": s["streak"],
                "won": s["won_this_week"],
                "pts": round(s["this_week_pts"], 1) if s["this_week_pts"] is not None else None,
                "opp_pts": round(s["opp_pts"], 1) if s["opp_pts"] is not None else None,
                "rank_change": s["rank_change"],
                "season_weeks": s["season_weeks"],
            } for s in storylines
        ],
        "high_scorer": {"team": high_scorer["team"], "pts": round(high_scorer["this_week_pts"], 1)} if high_scorer and high_scorer["this_week_pts"] else None,
        "low_scorer":  {"team": low_scorer["team"],  "pts": round(low_scorer["this_week_pts"], 1)} if low_scorer and low_scorer["this_week_pts"] else None,
        "biggest_blowout": biggest_blowout,
        "upsets": upsets,
        "hot_streaks": [{"team": s["team"], "streak": s["streak"]} for s in hot_streaks],
        "cold_streaks": [{"team": s["team"], "streak": s["streak"]} for s in cold_streaks],
        "big_movers": [
            {"team": s["team"], "from": s["rank_before"], "to": s["rank_after"]}
            for s in big_movers
        ],
        "playoff_race": playoff_race,
        "matchups": matchup_context,
        "next_week_preview": next_week_preview,
    }


def _generate_ai_storyline(payload: dict) -> dict:
    """Call OpenAI to generate the weekly recap column."""
    client = get_ai_client()

    schema = {
        "type": "object",
        "properties": {
            "headline": {"type": "string", "description": "Punchy headline (max 80 chars) for the week."},
            "paragraphs": {
                "type": "array",
                "items": {"type": "string"},
                "description": "2-4 paragraphs of league-wide storytelling. Each paragraph should be 2-4 sentences.",
            },
            "looking_ahead": {
                "type": "string",
                "description": "2-3 sentences on next week's game of the week (provided in next_week_preview). Empty string if no preview data is given.",
            },
        },
        "required": ["headline", "paragraphs", "looking_ahead"],
        "additionalProperties": False,
    }

    system_prompt = """
You are someone in a long-running fantasy football group chat writing a quick Tuesday recap. Casual, low-key, matter-of-fact. Like a friend who watched the games and has a few things to say - not performing, just talking.

Voice:
- Plain and direct. Say what happened, add a short take if it's worth it.
- Occasional slang is fine if it comes naturally - "ngl", "lowkey", "#noticing" - but use it once or twice at most. Don't chase it.
- No punchlines, no bits. Just observations.
- Contractions and fragments are fine. Short sentences are fine.
- Use team names and specific numbers - scores, records, streaks. That's the substance.

Hard rules:
- 2-4 paragraphs, 2-4 sentences each.
- DO NOT invent facts, scores, or players not in the data.
- No em dashes (–). Use a comma, period, or just rewrite the sentence.
- No markdown, bullets, or headers.
- Don't open with filler ("What a week", "Here's your recap"). Start with the actual news.
- Grounded tone - not mean, not hype, just real.
""".strip()

    user_prompt = f"""
Write a weekly recap column for {payload['league_name']}, Week {payload['week']}.

Weeks until playoffs: {payload['weeks_until_playoffs']} (playoffs start week {payload['week'] + payload['weeks_until_playoffs'] + 1 if payload['weeks_until_playoffs'] else payload['week']})

This week's matchups with head-to-head season history (a_pts/b_pts in prior_meetings correspond to team_a/team_b):
{json.dumps(payload['matchups'], indent=2)}

Standings (sorted by rank after this week). season_weeks shows every game this season so you can reference scoring trends and see if a team has been consistent, improving, or declining:
{json.dumps(payload['teams'], indent=2)}

High scorer: {json.dumps(payload['high_scorer'])}
Low scorer: {json.dumps(payload['low_scorer'])}
Biggest blowout: {json.dumps(payload['biggest_blowout'])}
Upsets (lower-seeded beat higher-seeded by 3+ ranks): {json.dumps(payload['upsets'])}
Hot streaks (3+ wins in a row): {json.dumps(payload['hot_streaks'])}
Cold streaks (2+ losses in a row): {json.dumps(payload['cold_streaks'])}
Big movers (rank moved 2+ spots): {json.dumps(payload['big_movers'])}
Playoff race: {json.dumps(payload['playoff_race'])}

Use the h2h and season_weeks data where it adds something real to the story - rematches, revenge games, scoring trends, a team peaking or fading. Lead with the most compelling storyline.

Next week's game of the week (already picked for you from rankings, playoff stakes, streaks, rematches, and missing starters):
{json.dumps(payload.get('next_week_preview'))}

For "looking_ahead": if next_week_preview is null, return an empty string. Otherwise write 2-3 sentences on that specific game_of_the_week - use the records, ranks, streaks, h2h, and any injured_a/injured_b starters (name + status). Say why it matters. Same voice as the recap. Do NOT restate every number; pick the ones that carry the story. Do not mention the other games unless it's natural.
""".strip()

    resp = client.responses.create(
        model="gpt-5-mini",
        input=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        text={
            "format": {
                "type": "json_schema",
                "name": "weekly_recap",
                "schema": schema,
            }
        },
    )
    return json.loads(clean_ai_text(resp.output_text.strip()))


def _render_recap_html(result: dict) -> str:
    headline = html.escape(str(result.get("headline") or "Week Recap"))
    paragraphs = result.get("paragraphs") or []
    paragraphs_html = "\n".join(
        f"<p style='margin:0 0 10px 0;'>{html.escape(str(p))}</p>"
        for p in paragraphs[:4] if str(p).strip()
    )

    return f"""
<div class="card" style="padding:18px 20px;margin-bottom:20px;">
  <div style="font-size:10px;font-weight:800;letter-spacing:.1em;color:var(--accent);margin-bottom:6px;">FROM THE GROUP CHAT</div>
  <div style="font-size:18px;font-weight:800;margin-bottom:12px;line-height:1.25;">{headline}</div>
  <div style="font-size:13px;line-height:1.55;color:var(--text);">
    {paragraphs_html}
  </div>
</div>
"""


def _render_next_week_html(preview: dict, looking_ahead: str) -> str:
    """Render the 'Game of the Week' look-ahead card from the deterministic
    preview data plus the AI's blurb. Returns '' when there's nothing to show."""
    if not preview or not preview.get("game_of_the_week"):
        return ""

    g = preview["game_of_the_week"]
    wk = preview.get("next_week")

    def _side(team: str, record: str, rank, align: str) -> str:
        rank_str = f"#{rank}" if rank else ""
        meta = " · ".join(x for x in [record, rank_str] if x)
        return (
            f"<div style='flex:1;min-width:0;text-align:{align};'>"
            f"<div style='font-weight:800;font-size:15px;line-height:1.2;overflow:hidden;"
            f"text-overflow:ellipsis;white-space:nowrap;'>{html.escape(str(team))}</div>"
            f"<div style='font-size:11px;color:var(--muted);margin-top:2px;'>{html.escape(meta)}</div>"
            f"</div>"
        )

    matchup_row = (
        "<div style='display:flex;align-items:center;gap:10px;margin:10px 0 12px 0;'>"
        + _side(g["team_a"], g["record_a"], g["rank_a"], "left")
        + "<div style='font-size:11px;font-weight:800;color:var(--muted);flex:0 0 auto;'>VS</div>"
        + _side(g["team_b"], g["record_b"], g["rank_b"], "right")
        + "</div>"
    )

    blurb_html = ""
    if looking_ahead and str(looking_ahead).strip():
        blurb_html = (
            f"<p style='margin:0 0 12px 0;font-size:13px;line-height:1.55;color:var(--text);'>"
            f"{html.escape(str(looking_ahead))}</p>"
        )

    # Injury chips (worst first, capped so the card stays tight).
    inj_chips = []
    for who, injured in ((g["team_a"], g.get("injured_a")), (g["team_b"], g.get("injured_b"))):
        for p in (injured or [])[:2]:
            label = f"{p.get('name')} ({p.get('status')})"
            inj_chips.append(
                f"<span class='player-badge player-badge-inj-out' "
                f"style='font-size:10px;'><i class='fa-solid fa-triangle-exclamation' "
                f"aria-hidden='true'></i> {html.escape(label)}</span>"
            )
    inj_html = ""
    if inj_chips:
        inj_html = (
            "<div style='display:flex;flex-wrap:wrap;gap:6px;margin-bottom:10px;'>"
            + "".join(inj_chips) + "</div>"
        )

    # Also-watch line.
    also = preview.get("also_watch") or []
    also_html = ""
    if also:
        items = " &nbsp;·&nbsp; ".join(
            f"{html.escape(str(a['team_a']))} vs {html.escape(str(a['team_b']))}" for a in also
        )
        also_html = (
            f"<div style='font-size:11px;color:var(--muted);border-top:1px solid var(--border,"
            f"rgba(148,163,184,0.2));padding-top:10px;'>Also worth watching: {items}</div>"
        )

    return f"""
<div class="card" style="padding:18px 20px;margin-bottom:20px;">
  <div style="font-size:10px;font-weight:800;letter-spacing:.1em;color:var(--accent);margin-bottom:6px;">NEXT WEEK{f' · WEEK {wk}' if wk else ''} · GAME OF THE WEEK</div>
  {matchup_row}
  {blurb_html}
  {inj_html}
  {also_html}
</div>
"""


def get_weekly_ai_recap(
        df_weekly: pd.DataFrame,
        matchups_by_week: dict,
        selected_week: int,
        team_by_rid: dict,
        league: dict,
        league_id: str,
        season,
        next_week_matchups: list | None = None,
        player_index: dict | None = None,
        value_by_pid: dict | None = None,
) -> tuple[str, str]:
    """Return (recap_column_html, next_week_card_html). Either may be ''.

    Both are produced by one AI call and cached together under one key (split on a
    sentinel) so the group-chat recap and the game-of-the-week look-ahead stay in
    sync and never cost two round-trips."""
    empty = ("", "")
    if df_weekly is None or df_weekly.empty:
        return empty

    cache_key = f"weekly_recap_{league_id}_{season}_w{selected_week}_v8_chat"
    cached = _load_recap_no_ttl(cache_key)
    if cached is not None:
        recap_html, _, next_html = cached.partition(_NEXT_WEEK_SPLIT)
        return recap_html, next_html

    try:
        payload = build_weekly_recap_payload(
            df_weekly, matchups_by_week, selected_week, team_by_rid, league,
            next_week_matchups=next_week_matchups,
            player_index=player_index,
            value_by_pid=value_by_pid,
        )
    except Exception as exc:
        logger.warning("[weekly-recap] payload build failed: %s", exc)
        return empty

    if not ai_available():
        return empty  # silently skip when AI is off

    try:
        result = _generate_ai_storyline(payload)
        recap_html = _render_recap_html(result)
        next_html = _render_next_week_html(
            payload.get("next_week_preview"), result.get("looking_ahead") or "",
        )
        save_cached_ai_text(cache_key, recap_html + _NEXT_WEEK_SPLIT + next_html)
        return recap_html, next_html
    except (AIRateLimitError, AIUnavailableError) as exc:
        logger.warning("[weekly-recap] AI unavailable: %s", exc)
        return empty
    except Exception as exc:
        logger.warning("[weekly-recap] AI error: %s", exc)
        return empty


def get_weekly_ai_recap_preview() -> tuple[str, str]:
    """Static sample for preview mode: the recap column plus a game-of-the-week card."""
    recap_html = _render_recap_html({
        "headline": "Gridiron Ghosts got the rematch and it went worse than the first time",
        "paragraphs": [
            "Gridiron Ghosts lost to Dynasty Kings again. Week 7 rematch, same result, bigger margin this time. They're 0-2 against them on the season and the two losses account for the entire gap between their records. Not ideal.",
            "Slim Reaper Lemonade is doing that thing where they keep putting up big scores and losing anyway. Top-three scorer three weeks in a row, 1-2 in that stretch. Their points total is second in the league and they're sitting at 3-4. At some point that has to even out.",
            "Three teams are tied at 4-3 with five weeks left and two of them play each other in Week 8. Someone's going to separate. The bubble is real and a couple people in this league haven't fully processed that yet.",
            "Also JiggyJay30 scored 98 this week after putting up 134 last week. No notes. Fantasy is what it is.",
        ],
    })
    next_html = _render_next_week_html(
        {
            "next_week": 8,
            "weeks_left_after": 5,
            "game_of_the_week": {
                "team_a": "Dynasty Kings", "team_b": "Blitz Brigade",
                "record_a": "6-1", "record_b": "5-2",
                "rank_a": 1, "rank_b": 3,
                "streak_a": "W4", "streak_b": "W2",
                "h2h": {"meetings": 1, "a_wins": 1, "b_wins": 0},
                "injured_a": [],
                "injured_b": [{"name": "Bijan Robinson", "pos": "RB", "status": "OUT", "value": 8000}],
                "reasons": ["two of the league's best", "Dynasty Kings on a W4 run"],
                "score": 22.5,
            },
            "also_watch": [
                {"team_a": "Redzone Rebels", "team_b": "Endzone Elite", "reasons": ["neighbors in the standings"]},
            ],
        },
        "The 1 vs 3 game everyone circled, and it lands with Blitz Brigade down Bijan Robinson (OUT). "
        "Dynasty Kings won the first meeting and haven't lost since. Blitz has to find points somewhere or the gap at the top gets real.",
    )
    return recap_html, next_html
