from __future__ import annotations

import html
import json
import logging
from math import erf, sqrt

import pandas as pd

from dashboard_services.ai.cache import AI_CACHE_DIR, save_cached_ai_text
from dashboard_services.ai.client import (
    AIRateLimitError,
    AIUnavailableError,
    clean_ai_text,
    get_ai_client,
)
from dashboard_services.ai.renderer import ai_available
from utils.all_play import all_play_analysis

logger = logging.getLogger(__name__)

# Sentinel that joins the recap column and the game-of-the-week card in a single
# cache entry (they're generated by one AI call). Chosen so it can never appear
# in rendered HTML.
_NEXT_WEEK_SPLIT = "<!--__NEXT_WEEK_CARD__-->"


def _load_recap_no_ttl(cache_key: str) -> str | None:
    """Load a cached weekly recap without applying the global TTL.
    The cache key includes the league/season/week, so once a week's
    recap is written it remains valid until that week regenerates."""
    path = AI_CACHE_DIR / f"{cache_key}.json"
    if not path.exists():
        return None
    try:
        obj = json.loads(path.read_text(encoding="utf-8"))
        return obj.get("content")
    except Exception:
        return None


def _streak_for(results: list[str]) -> str:
    """Compute current streak like 'W3' or 'L2' from a list of 'W'/'L' results."""
    if not results:
        return "-"
    last = results[-1]
    n = 1
    for r in reversed(results[:-1]):
        if r == last:
            n += 1
        else:
            break
    return f"{last}{n}"


def _build_team_storylines(
        df_weekly: pd.DataFrame,
        selected_week: int,
        team_by_rid: dict,
) -> list[dict]:
    """For each team, compute record/rank/streak before and after the selected week."""
    fin_df = df_weekly[(df_weekly["finalized"] == True) & (df_weekly["week"] <= selected_week)].copy()
    if fin_df.empty:
        return []

    fin_df["win"] = fin_df["points"] > fin_df["points_against"]

    # Build per-team history sorted by week
    teams: dict[str, dict] = {}
    for rid, grp in fin_df.groupby("roster_id"):
        grp = grp.sort_values("week")
        results = ["W" if w else "L" for w in grp["win"].tolist()]
        # Snapshot through selected_week
        owner = str(grp["owner"].iloc[0])
        _av = ""
        if "avatar" in grp.columns:
            _av0 = grp["avatar"].iloc[0]
            _av = str(_av0) if pd.notna(_av0) else ""
        teams[str(rid)] = {
            "rid": str(rid),
            "team": team_by_rid.get(str(rid), owner),
            "owner": owner,
            "avatar": _av,
            "results": results,
            "weeks": [int(w) for w in grp["week"].tolist()],
            "pts_by_week": [float(p) for p in grp["points"].tolist()],
        }

    # Compute snapshots BEFORE selected_week
    snap_before: dict[str, dict] = {}
    snap_after: dict[str, dict] = {}
    for rid, t in teams.items():
        # Before this week: only weeks < selected_week
        before_idx = [i for i, w in enumerate(t["weeks"]) if w < selected_week]
        wins_b = sum(1 for i in before_idx if t["results"][i] == "W")
        losses_b = sum(1 for i in before_idx if t["results"][i] == "L")
        pf_b = sum(t["pts_by_week"][i] for i in before_idx)
        snap_before[rid] = {
            "wins": wins_b, "losses": losses_b, "pf": pf_b,
            "streak": _streak_for([t["results"][i] for i in before_idx]),
        }
        # After (through this week, inclusive)
        wins_a = sum(1 for r in t["results"] if r == "W")
        losses_a = sum(1 for r in t["results"] if r == "L")
        pf_a = sum(t["pts_by_week"])
        snap_after[rid] = {
            "wins": wins_a, "losses": losses_a, "pf": pf_a,
            "streak": _streak_for(t["results"]),
        }

    # Compute rank (1 = best) by wins then PF
    def _rank(snap_map):
        items = list(snap_map.items())
        items.sort(key=lambda x: (-x[1]["wins"], -x[1]["pf"]))
        return {rid: i + 1 for i, (rid, _s) in enumerate(items)}

    rank_before = _rank(snap_before)
    rank_after = _rank(snap_after)

    # This-week result per team
    week_df = df_weekly[(df_weekly["week"] == selected_week) & (df_weekly["finalized"] == True)]
    week_result_by_rid: dict[str, dict] = {}
    for _, row in week_df.iterrows():
        rid = str(row.get("roster_id"))
        week_result_by_rid[rid] = {
            "pts": float(row.get("points") or 0),
            "opp_pts": float(row.get("points_against") or 0),
            "won": bool(row.get("points", 0) > row.get("points_against", 0)),
        }

    storylines = []
    for rid, t in teams.items():
        wr = week_result_by_rid.get(rid, {})
        before = snap_before[rid]
        after = snap_after[rid]

        season_weeks = [
            {
                "week": t["weeks"][i],
                "result": t["results"][i],
                "pts": round(t["pts_by_week"][i], 1),
            }
            for i in range(len(t["weeks"]))
        ]

        storylines.append({
            "rid": rid,
            "team": t["team"],
            "owner": t["owner"],
            "avatar": t.get("avatar", ""),
            "this_week_pts": wr.get("pts"),
            "opp_pts": wr.get("opp_pts"),
            "won_this_week": wr.get("won"),
            "record_before": f"{before['wins']}-{before['losses']}",
            "record_after": f"{after['wins']}-{after['losses']}",
            "rank_before": rank_before.get(rid),
            "rank_after": rank_after.get(rid),
            "rank_change": (rank_before.get(rid) or 0) - (rank_after.get(rid) or 0),  # +ve = moved up
            "streak": after["streak"],
            "streak_before": before["streak"],
            "pf_after": round(after["pf"], 1),
            "season_weeks": season_weeks,
        })

    storylines.sort(key=lambda x: x["rank_after"] or 99)
    return storylines


def _build_matchup_context(
        df_weekly: pd.DataFrame,
        selected_week: int,
        team_by_rid: dict,
) -> list[dict]:
    """For each matchup this week, compute h2h record and prior meetings this season."""
    fin_df = df_weekly[df_weekly["finalized"] == True].copy()
    if fin_df.empty:
        return []

    # (week, matchup_id) -> [(rid, pts)]
    pairs: dict[tuple, list] = {}
    for _, row in fin_df.iterrows():
        key = (int(row["week"]), int(row.get("matchup_id") or 0))
        pairs.setdefault(key, []).append((str(row["roster_id"]), float(row["points"])))

    this_week = {k: v for k, v in pairs.items() if k[0] == selected_week and len(v) == 2}

    result = []
    for (_w, _mid), sides in this_week.items():
        rid_a, pts_a = sides[0]
        rid_b, pts_b = sides[1]
        team_a = team_by_rid.get(rid_a, rid_a)
        team_b = team_by_rid.get(rid_b, rid_b)

        prior = []
        for (w, _m), s in pairs.items():
            if w >= selected_week or len(s) != 2:
                continue
            if {s[0][0], s[1][0]} == {rid_a, rid_b}:
                a_side = next(x for x in s if x[0] == rid_a)
                b_side = next(x for x in s if x[0] == rid_b)
                prior.append({
                    "week": w,
                    "a_pts": round(a_side[1], 1),
                    "b_pts": round(b_side[1], 1),
                    "winner": team_a if a_side[1] > b_side[1] else team_b,
                })

        prior.sort(key=lambda x: x["week"])
        a_wins = sum(1 for p in prior if p["winner"] == team_a)
        b_wins = sum(1 for p in prior if p["winner"] == team_b)

        entry: dict = {
            "team_a": team_a,
            "team_b": team_b,
            "team_a_pts": round(pts_a, 1),
            "team_b_pts": round(pts_b, 1),
            "winner": team_a if pts_a > pts_b else team_b,
        }
        if prior:
            entry["h2h"] = {
                "team_a_wins": a_wins,
                "team_b_wins": b_wins,
                "prior_meetings": prior,
            }
        result.append(entry)

    return result


# Statuses that keep a starter out of a lineup. QUESTIONABLE is handled
# separately as a "will he play?" watch, not a hard miss.
_OUT_STATUSES = {"OUT", "IR", "DOUBTFUL", "PUP", "NFI", "SUSP"}
_MAYBE_STATUSES = {"QUESTIONABLE", "Q"}

# How the six signals combine into the game-of-the-week score. Every signal is
# normalized to 0-1 first (below), so these weights — not raw scales — decide
# what wins. Stakes and closeness lead: what's on the line and whether it'll be
# close is the heart of a great game.
_SIGNAL_WEIGHTS = {
    "stakes":    1.10,
    "closeness": 1.00,
    "strength":  0.90,
    "rivalry":   0.60,
    "drama":     0.60,
    "heat":      0.50,
}
# Projected points at risk (missing + half of questionable/bye) that saturate
# the drama / star-watch signal.
_DRAMA_FULL = 22.0
# Rough dynasty-value → weekly-points proxy, used only when a live weekly
# projection isn't available for an injured starter.
_VALUE_TO_PPG = 300.0


def _prior_series(
        df_weekly: pd.DataFrame,
        rid_a: str,
        rid_b: str,
        upto_week: int,
) -> tuple[int, int, int]:
    """Season head-to-head between two rosters through ``upto_week`` (inclusive):
    (meetings, rid_a wins, rid_b wins)."""
    fin = df_weekly[(df_weekly["finalized"] == True) & (df_weekly["week"] <= upto_week)]
    meetings = a_wins = b_wins = 0
    for (_w, _mid), g in fin.groupby(["week", "matchup_id"]):
        if len(g) != 2:
            continue
        rids = [str(r) for r in g["roster_id"].tolist()]
        if str(rid_a) not in rids or str(rid_b) not in rids:
            continue
        ga = g[g["roster_id"].astype(str) == str(rid_a)].iloc[0]
        gb = g[g["roster_id"].astype(str) == str(rid_b)].iloc[0]
        meetings += 1
        if float(ga["points"]) > float(gb["points"]):
            a_wins += 1
        elif float(gb["points"]) > float(ga["points"]):
            b_wins += 1
    return meetings, a_wins, b_wins


def _all_play_strength(df_weekly: pd.DataFrame, upto_week: int) -> dict:
    """{rid: all-play win pct in [0,1]} through ``upto_week`` — a
    schedule-independent strength rating, far steadier than a W-L seed early in
    the year. A team that would beat most of the league every week rates high
    even if its head-to-head luck has been bad."""
    fin = df_weekly[(df_weekly["finalized"] == True) & (df_weekly["week"] <= upto_week)]
    weekly_scores: dict = {}
    for _, r in fin.iterrows():
        weekly_scores.setdefault(int(r["week"]), {})[str(r["roster_id"])] = float(r.get("points") or 0.0)
    ap = all_play_analysis(weekly_scores, {})
    return {rid: v["all_play_pct"] for rid, v in ap.items()}


def _proj_win_prob(starters_a: list, starters_b: list, proj_by_pid: dict) -> float:
    """Team A's win probability from projections alone, modeling each starter as
    normal(proj, sigma). For an upcoming week every starter is pending, so this is
    a pure projection-based read of how close the game projects."""
    def _stats(starters):
        total = var = 0.0
        for p in (starters or []):
            proj = float(proj_by_pid.get(str(p.get("pid") or ""), 0.0) or 0.0)
            total += proj
            sigma = max(0.4 * proj, 4.0)
            var += sigma * sigma
        return total, var

    ta, va = _stats(starters_a)
    tb, vb = _stats(starters_b)
    cv = va + vb
    if cv < 1e-6:
        return 0.5 if abs(ta - tb) < 1e-9 else (1.0 if ta > tb else 0.0)
    z = (ta - tb) / (sqrt(cv) * sqrt(2.0))
    return max(0.01, min(0.99, 0.5 * (1.0 + erf(z))))


def _team_proj_total(starters: list, proj_by_pid: dict) -> float:
    return sum(float(proj_by_pid.get(str(p.get("pid") or ""), 0.0) or 0.0) for p in (starters or []))


def _starter_flags(
        team_block: dict,
        player_index: dict,
        proj_by_pid: dict,
        value_by_pid: dict,
        playing_teams: set,
) -> tuple[list, list, list, float]:
    """Categorize a team's projected starters into out / questionable / on-bye,
    each carrying its weekly projection (the real 'how much does losing them
    hurt' measure) with dynasty value as a fallback. Returns
    (out, questionable, bye, points_at_risk)."""
    out: list[dict] = []
    maybe: list[dict] = []
    byes: list[dict] = []
    risk = 0.0
    for p in (team_block.get("starters") or []):
        pid = str(p.get("pid") or "")
        info = player_index.get(pid) or {}
        raw = str(info.get("injury_status") or info.get("status") or "").strip().upper()
        proj = float(proj_by_pid.get(pid, 0.0) or 0.0)
        impact = proj if proj > 0 else (value_by_pid.get(pid, 0.0) or 0.0) / _VALUE_TO_PPG
        nfl = str(p.get("nfl") or "").upper()
        entry = {
            "name": p.get("name"), "pos": p.get("pos"),
            "proj": round(proj, 1), "value": value_by_pid.get(pid, 0.0),
        }
        if raw in _OUT_STATUSES:
            out.append({**entry, "status": raw})
            risk += impact
        elif raw in _MAYBE_STATUSES:
            maybe.append({**entry, "status": "QUESTIONABLE"})
            risk += impact * 0.5
        elif playing_teams and nfl and nfl not in playing_teams:
            byes.append({**entry, "status": "BYE"})
            risk += impact * 0.5

    out.sort(key=lambda x: (x["proj"], x["value"] or 0.0), reverse=True)
    maybe.sort(key=lambda x: (x["proj"], x["value"] or 0.0), reverse=True)
    byes.sort(key=lambda x: (x["proj"], x["value"] or 0.0), reverse=True)
    return out, maybe, byes, risk


def _regular_stakes(
        rank_a: int,
        rank_b: int,
        playoff_teams: int,
        weeks_left_after: int,
        has_bye_seed: bool,
) -> tuple[float, str | None]:
    """Normalized [0,1] playoff stakes for a regular-season game, plus a label
    for why it matters. Stakes ramp up as the field tightens near the cutline."""
    if not playoff_teams:
        return 0.0, None
    # Playoff stakes only ramp up over the last ~6 weeks; earlier than that the
    # standings are too fluid for a single game to be a "decider".
    urgency = max(0.0, min(1.0, 1.0 - weeks_left_after / 6.0))
    if urgency <= 0.0:
        return 0.0, None
    cut = playoff_teams
    prox_a = max(0.0, 1.0 - abs(rank_a - cut) / 3.0)
    prox_b = max(0.0, 1.0 - abs(rank_b - cut) / 3.0)
    value = urgency * (prox_a + prox_b) / 2.0
    label: str | None = None

    # Both teams straddling the cutline — a direct bubble game (weight by urgency).
    if abs(rank_a - cut) <= 1 and abs(rank_b - cut) <= 1:
        value = max(value, urgency * (1.0 if weeks_left_after == 0 else 0.75))
        label = "Win-and-in" if weeks_left_after == 0 else "Playoff bubble decider"

    # #1 seed / first-round bye on the line between two of the best.
    if has_bye_seed and rank_a <= 2 and rank_b <= 2:
        seed_val = urgency * 0.9
        if seed_val >= value:
            value, label = seed_val, "Top seed & first-round bye on the line"

    return min(1.0, value), label


def _reason_bits(
        top_factor: str | None,
        *,
        sa: dict, sb: dict, rank_a: int, rank_b: int, num_teams: int,
        win_prob: float, meetings: int, stakes_label: str | None,
        is_playoff: bool, round_label: str, top_star: dict | None,
) -> str:
    """A short, specific headline explaining why THIS is the game of the week,
    drawn from the dominant scoring factor."""
    top_third = max(2, round(num_teams / 3))

    if top_factor == "stakes":
        return round_label if is_playoff else (stakes_label or "Playoff seeding on the line")
    if top_factor == "closeness":
        lo = round(min(win_prob, 1 - win_prob) * 100)
        return f"Dead heat on paper ({lo}-{100 - lo})"
    if top_factor == "strength":
        if rank_a <= 2 and rank_b <= 2:
            return "Two of the top teams, head to head"
        if rank_a <= top_third and rank_b <= top_third:
            return "Two of the league's best"
        return "Heavyweight matchup"
    if top_factor == "rivalry":
        return "The rubber match" if meetings >= 2 else "A rematch with a score to settle"
    if top_factor == "heat":
        hot = [s for s in (sa, sb) if str(s.get("streak") or "").startswith("W")
               and int(str(s.get("streak"))[1:] or 0) >= 2]
        if len(hot) == 2:
            return "Two red-hot teams collide"
        if hot:
            return f"{hot[0]['team']} is rolling ({hot[0]['streak']})"
        return "A momentum swing game"
    if top_factor == "drama" and top_star:
        return f"Star on the shelf: {top_star['name']} ({top_star['status']})"
    return "The week's headline matchup"


def _build_next_week_preview(
        df_weekly: pd.DataFrame,
        storyline_by_rid: dict,
        selected_week: int,
        playoff_start: int,
        playoff_teams: int,
        num_teams: int,
        nctx: dict,
) -> dict | None:
    """Score each of next week's matchups on six normalized signals — playoff
    stakes, projected closeness, team strength (all-play), a rivalry angle,
    star-availability drama, and momentum — combine them with intentional
    weights, and pick the game of the week. Records which signal drove the pick
    so the card and the AI can say *why*. Deterministic and data-grounded; the AI
    only narrates the choice."""
    matchups = (nctx or {}).get("matchups") or []
    if not matchups:
        return None

    next_week = selected_week + 1
    is_playoff = bool((nctx or {}).get("is_playoff"))
    weeks_left_after = max(0, playoff_start - 1 - next_week)
    proj_by_pid = (nctx or {}).get("proj_by_pid") or {}
    player_index = (nctx or {}).get("player_index") or {}
    value_by_pid = (nctx or {}).get("value_by_pid") or {}
    playing_teams = (nctx or {}).get("playing_teams") or set()
    round_label = (nctx or {}).get("playoff_round_label") or "Playoff game"
    strength = _all_play_strength(df_weekly, selected_week)
    has_bye_seed = bool(playoff_teams) and playoff_teams not in (2, 4, 8, 16)

    games: list[dict] = []
    for m in matchups:
        left = m.get("left") or {}
        right = m.get("right") or {}
        rid_a = str(left.get("roster_id") or "")
        rid_b = str(right.get("roster_id") or "")
        sa = storyline_by_rid.get(rid_a)
        sb = storyline_by_rid.get(rid_b)
        if not sa or not sb:
            continue

        rank_a = sa["rank_after"] or num_teams
        rank_b = sb["rank_after"] or num_teams
        meetings, a_wins, b_wins = _prior_series(df_weekly, rid_a, rid_b, selected_week)
        out_a, maybe_a, bye_a, risk_a = _starter_flags(left, player_index, proj_by_pid, value_by_pid, playing_teams)
        out_b, maybe_b, bye_b, risk_b = _starter_flags(right, player_index, proj_by_pid, value_by_pid, playing_teams)

        # ── Six signals, each normalized to [0, 1] ─────────────────────────────
        signals: dict[str, float] = {}

        # Team strength: average all-play win pct of the two teams.
        signals["strength"] = (strength.get(rid_a, 0.5) + strength.get(rid_b, 0.5)) / 2.0

        # Closeness: projected win prob near 50/50. Only trust it when both teams
        # actually have projections, else an empty slate reads as a false 50/50.
        have_proj = _team_proj_total(left.get("starters"), proj_by_pid) > 0 and \
            _team_proj_total(right.get("starters"), proj_by_pid) > 0
        win_prob = _proj_win_prob(left.get("starters"), right.get("starters"), proj_by_pid) if have_proj else 0.5
        signals["closeness"] = max(0.0, 1.0 - 2.0 * abs(win_prob - 0.5)) if have_proj else 0.0

        # Momentum: combined win-streak heat.
        def _hot(s):
            st = str(s.get("streak") or "")
            n = int(st[1:] or 0) if st.startswith("W") else 0
            return n if n >= 2 else 0
        signals["heat"] = min(1.0, (_hot(sa) + _hot(sb)) / 8.0)

        # Rivalry: a season series already underway.
        signals["rivalry"] = 0.0 if meetings == 0 else (0.6 if meetings == 1 else 1.0)

        # Drama: projected points at risk from missing / questionable / bye stars.
        signals["drama"] = min(1.0, (risk_a + risk_b) / _DRAMA_FULL)

        # Stakes: playoff picture (elimination in the playoffs themselves).
        if is_playoff:
            stakes_val, stakes_label = 1.0, round_label
        else:
            stakes_val, stakes_label = _regular_stakes(rank_a, rank_b, playoff_teams, weeks_left_after, has_bye_seed)
        signals["stakes"] = stakes_val

        # ── Weighted score + which factor drove it ─────────────────────────────
        contrib = {k: _SIGNAL_WEIGHTS[k] * v for k, v in signals.items()}
        score = sum(contrib.values())
        top_factor = max(contrib, key=lambda k: contrib[k]) if score > 1e-9 else None

        all_stars = out_a + out_b + maybe_a + maybe_b
        top_star = max(all_stars, key=lambda x: (x["proj"], x["value"] or 0.0)) if all_stars else None
        headline = _reason_bits(
            top_factor, sa=sa, sb=sb, rank_a=rank_a, rank_b=rank_b, num_teams=num_teams,
            win_prob=win_prob, meetings=meetings, stakes_label=stakes_label,
            is_playoff=is_playoff, round_label=round_label, top_star=top_star,
        )

        # Ordered supporting reasons (every meaningfully-firing factor, best first).
        phrase = {
            "stakes": stakes_label or ("elimination game" if is_playoff else None),
            "closeness": f"projects as a {round(min(win_prob, 1 - win_prob) * 100)}/"
                         f"{100 - round(min(win_prob, 1 - win_prob) * 100)} coin-flip" if signals["closeness"] >= 0.4 else None,
            "strength": "two of the league's best" if signals["strength"] >= 0.55 else None,
            "rivalry": ("rubber match" if meetings >= 2 else "a rematch") if meetings else None,
            "drama": f"{top_star['name']} ({top_star['status']}) in doubt" if top_star else None,
            "heat": (f"{sa['team']} on {sa['streak']}" if _hot(sa) >= _hot(sb) and _hot(sa)
                     else (f"{sb['team']} on {sb['streak']}" if _hot(sb) else None)),
        }
        reasons = [phrase[k] for k in sorted(contrib, key=lambda k: -contrib[k])
                   if phrase.get(k) and contrib[k] > 0.05]

        games.append({
            "team_a": sa["team"], "team_b": sb["team"],
            "avatar_a": sa.get("avatar", ""), "avatar_b": sb.get("avatar", ""),
            "record_a": sa["record_after"], "record_b": sb["record_after"],
            "rank_a": rank_a, "rank_b": rank_b,
            "streak_a": sa.get("streak"), "streak_b": sb.get("streak"),
            "win_prob_a": round(win_prob * 100) if have_proj else None,
            "proj_a": round(_team_proj_total(left.get("starters"), proj_by_pid), 1) if have_proj else None,
            "proj_b": round(_team_proj_total(right.get("starters"), proj_by_pid), 1) if have_proj else None,
            "h2h": {"meetings": meetings, "a_wins": a_wins, "b_wins": b_wins} if meetings else None,
            "out_a": out_a, "maybe_a": maybe_a, "bye_a": bye_a,
            "out_b": out_b, "maybe_b": maybe_b, "bye_b": bye_b,
            "why": headline, "top_factor": top_factor,
            "reasons": reasons,
            "score": round(score, 3),
        })

    if not games:
        return None

    games.sort(key=lambda g: -g["score"])
    top = games[0]
    # A quiet slate (nothing scored high) is framed honestly rather than hyped.
    quiet_week = top["score"] < 0.9
    # A near-tied runner-up is surfaced as a co-headliner.
    close_second = len(games) > 1 and games[1]["score"] >= top["score"] * 0.9

    return {
        "next_week": next_week,
        "is_playoff": is_playoff,
        "round_label": round_label if is_playoff else None,
        "weeks_left_after": weeks_left_after,
        "quiet_week": quiet_week,
        "close_second": close_second,
        "as_of": (nctx or {}).get("as_of"),
        "game_of_the_week": top,
        "also_watch": [
            {"team_a": g["team_a"], "team_b": g["team_b"], "why": g["why"]}
            for g in games[1:3]
        ],
    }


def build_weekly_recap_payload(
        df_weekly: pd.DataFrame,
        matchups_by_week: dict,
        selected_week: int,
        team_by_rid: dict,
        league: dict,
        next_week_ctx: dict | None = None,
) -> dict:
    storylines = _build_team_storylines(df_weekly, selected_week, team_by_rid)
    matchup_context = _build_matchup_context(df_weekly, selected_week, team_by_rid)

    settings = (league or {}).get("settings") or {}
    playoff_start = int(settings.get("playoff_week_start") or 14)
    playoff_teams = int(settings.get("playoff_teams") or 6)
    league_name = (league or {}).get("name") or "the league"

    weeks_until_playoffs = max(0, playoff_start - 1 - selected_week)

    # Identify upsets (lower-ranked-before beats higher-ranked-before)
    week_matchups_raw = matchups_by_week.get(selected_week) or []
    upsets = []
    biggest_blowout = None
    for m in week_matchups_raw:
        l = m.get("left") or {}
        r = m.get("right") or {}
        l_rid = str(l.get("roster_id") or "")
        r_rid = str(r.get("roster_id") or "")
        l_pts = float(l.get("pts_total") or 0)
        r_pts = float(r.get("pts_total") or 0)
        if l_pts == r_pts:
            continue
        winner_rid, loser_rid = (l_rid, r_rid) if l_pts > r_pts else (r_rid, l_rid)
        winner_pts, loser_pts = (l_pts, r_pts) if l_pts > r_pts else (r_pts, l_pts)
        winner = next((s for s in storylines if s["team"] == team_by_rid.get(winner_rid)
                       or s["owner"] == (l.get("username") if winner_rid == l_rid else r.get("username"))), None)
        loser = next((s for s in storylines if s["team"] == team_by_rid.get(loser_rid)
                      or s["owner"] == (l.get("username") if loser_rid == l_rid else r.get("username"))), None)
        margin = winner_pts - loser_pts
        if winner and loser and winner["rank_before"] and loser["rank_before"]:
            if winner["rank_before"] > loser["rank_before"] + 2:
                upsets.append({
                    "winner": winner["team"], "loser": loser["team"],
                    "winner_rank_before": winner["rank_before"],
                    "loser_rank_before": loser["rank_before"],
                    "margin": round(margin, 1),
                })
        if biggest_blowout is None or margin > biggest_blowout["margin"]:
            biggest_blowout = {
                "winner": team_by_rid.get(winner_rid, "Unknown"),
                "loser": team_by_rid.get(loser_rid, "Unknown"),
                "winner_pts": round(winner_pts, 1),
                "loser_pts": round(loser_pts, 1),
                "margin": round(margin, 1),
            }

    # Playoff race tightness: gap between cutline team and just-outside team
    playoff_race = None
    if storylines and playoff_teams and len(storylines) > playoff_teams:
        cutline = storylines[playoff_teams - 1]
        bubble = storylines[playoff_teams]
        wins_gap = (cutline["record_after"].split("-")[0] != bubble["record_after"].split("-")[0])
        playoff_race = {
            "cutline_team": cutline["team"],
            "cutline_record": cutline["record_after"],
            "bubble_team": bubble["team"],
            "bubble_record": bubble["record_after"],
            "tight": not wins_gap,
        }

    # Notable highlights
    high_scorer = max(storylines, key=lambda x: x["this_week_pts"] or 0) if storylines else None
    low_scorer = min(storylines, key=lambda x: x["this_week_pts"] if x["this_week_pts"] is not None else 1e9) if storylines else None
    hot_streaks = [s for s in storylines if s["streak"].startswith("W") and int(s["streak"][1:] or 0) >= 3]
    cold_streaks = [s for s in storylines if s["streak"].startswith("L") and int(s["streak"][1:] or 0) >= 2]
    big_movers = sorted([s for s in storylines if abs(s["rank_change"]) >= 2],
                        key=lambda x: -abs(x["rank_change"]))[:3]

    num_teams = len(storylines)
    storyline_by_rid = {str(s["rid"]): s for s in storylines}
    next_week_preview = _build_next_week_preview(
        df_weekly,
        storyline_by_rid,
        selected_week,
        playoff_start,
        playoff_teams,
        num_teams,
        next_week_ctx or {},
    )

    return {
        "league_name": league_name,
        "week": selected_week,
        "weeks_until_playoffs": weeks_until_playoffs,
        "playoff_teams": playoff_teams,
        "teams": [
            {
                "team": s["team"],
                "rank_before": s["rank_before"],
                "rank_after": s["rank_after"],
                "record_after": s["record_after"],
                "streak": s["streak"],
                "won": s["won_this_week"],
                "pts": round(s["this_week_pts"], 1) if s["this_week_pts"] is not None else None,
                "opp_pts": round(s["opp_pts"], 1) if s["opp_pts"] is not None else None,
                "rank_change": s["rank_change"],
                "season_weeks": s["season_weeks"],
            } for s in storylines
        ],
        "high_scorer": {"team": high_scorer["team"], "pts": round(high_scorer["this_week_pts"], 1)} if high_scorer and high_scorer["this_week_pts"] else None,
        "low_scorer":  {"team": low_scorer["team"],  "pts": round(low_scorer["this_week_pts"], 1)} if low_scorer and low_scorer["this_week_pts"] else None,
        "biggest_blowout": biggest_blowout,
        "upsets": upsets,
        "hot_streaks": [{"team": s["team"], "streak": s["streak"]} for s in hot_streaks],
        "cold_streaks": [{"team": s["team"], "streak": s["streak"]} for s in cold_streaks],
        "big_movers": [
            {"team": s["team"], "from": s["rank_before"], "to": s["rank_after"]}
            for s in big_movers
        ],
        "playoff_race": playoff_race,
        "matchups": matchup_context,
        "next_week_preview": next_week_preview,
    }


def _generate_ai_storyline(payload: dict) -> dict:
    """Call OpenAI to generate the weekly recap column."""
    client = get_ai_client()

    schema = {
        "type": "object",
        "properties": {
            "headline": {"type": "string", "description": "Punchy headline (max 80 chars) for the week."},
            "paragraphs": {
                "type": "array",
                "items": {"type": "string"},
                "description": "2-4 paragraphs of league-wide storytelling. Each paragraph should be 2-4 sentences.",
            },
            "looking_ahead": {
                "type": "string",
                "description": "2-3 sentences on next week's game of the week (provided in next_week_preview), in the exact same group-chat voice as the recap paragraphs. Empty string if no preview data is given.",
            },
        },
        "required": ["headline", "paragraphs", "looking_ahead"],
        "additionalProperties": False,
    }

    system_prompt = """
You are someone in a long-running fantasy football group chat writing a quick Tuesday recap. Casual, low-key, matter-of-fact. Like a friend who watched the games and has a few things to say - not performing, just talking.

Voice:
- Plain and direct. Say what happened, add a short take if it's worth it.
- Occasional slang is fine if it comes naturally - "ngl", "lowkey", "#noticing" - but use it once or twice at most. Don't chase it.
- No punchlines, no bits. Just observations.
- Contractions and fragments are fine. Short sentences are fine.
- Use team names and specific numbers - scores, records, streaks. That's the substance.

Hard rules:
- 2-4 paragraphs, 2-4 sentences each.
- DO NOT invent facts, scores, or players not in the data.
- No em dashes (–). Use a comma, period, or just rewrite the sentence.
- No markdown, bullets, or headers.
- Don't open with filler ("What a week", "Here's your recap"). Start with the actual news.
- Grounded tone - not mean, not hype, just real.
""".strip()

    user_prompt = f"""
Write a weekly recap column for {payload['league_name']}, Week {payload['week']}.

Weeks until playoffs: {payload['weeks_until_playoffs']} (playoffs start week {payload['week'] + payload['weeks_until_playoffs'] + 1 if payload['weeks_until_playoffs'] else payload['week']})

This week's matchups with head-to-head season history (a_pts/b_pts in prior_meetings correspond to team_a/team_b):
{json.dumps(payload['matchups'], indent=2)}

Standings (sorted by rank after this week). season_weeks shows every game this season so you can reference scoring trends and see if a team has been consistent, improving, or declining:
{json.dumps(payload['teams'], indent=2)}

High scorer: {json.dumps(payload['high_scorer'])}
Low scorer: {json.dumps(payload['low_scorer'])}
Biggest blowout: {json.dumps(payload['biggest_blowout'])}
Upsets (lower-seeded beat higher-seeded by 3+ ranks): {json.dumps(payload['upsets'])}
Hot streaks (3+ wins in a row): {json.dumps(payload['hot_streaks'])}
Cold streaks (2+ losses in a row): {json.dumps(payload['cold_streaks'])}
Big movers (rank moved 2+ spots): {json.dumps(payload['big_movers'])}
Playoff race: {json.dumps(payload['playoff_race'])}

Use the h2h and season_weeks data where it adds something real to the story - rematches, revenge games, scoring trends, a team peaking or fading. Lead with the most compelling storyline.

Next week's game of the week (already picked for you). The "why" field is the single biggest reason it was chosen (playoff stakes, a projected coin-flip, two top teams, a rivalry rematch, a missing star, or momentum); "reasons" lists the supporting angles; out_a/out_b/maybe_a/maybe_b/bye_a/bye_b are missing, questionable, and on-bye starters with their projections:
{json.dumps(payload.get('next_week_preview'))}

For "looking_ahead": if next_week_preview is null, return an empty string. Otherwise write 2-3 sentences on that game_of_the_week in the SAME low-key group-chat voice as the recap paragraphs - like you're texting the group about the game you're most looking forward to next week. Jump straight into the matchup - the teams, the records, the stakes. Never announce or label the pick: the card already shows a "Game of the Week" banner, so any opener that names it as the game of the week (or "the marquee matchup", "the one to watch", etc.), or that spells out the reason as a because-clause, reads as copy-paste filler. Instead let the reason it matters (playoff stakes, a coin-flip, two top teams, a rivalry rematch, a missing star, momentum) come through inside what you say about the teams - this blurb is the only place that reason reaches the reader, so it has to land, just woven in rather than declared. Lead with whatever's actually interesting. Ground it in the records, ranks, streaks, h2h, or the specific missing starter (name + status), but do NOT restate every number. Only mention the other games if it's natural.
""".strip()

    resp = client.responses.create(
        model="gpt-5-mini",
        input=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        text={
            "format": {
                "type": "json_schema",
                "name": "weekly_recap",
                "schema": schema,
            }
        },
    )
    return json.loads(clean_ai_text(resp.output_text.strip()))


def _render_recap_html(result: dict) -> str:
    headline = html.escape(str(result.get("headline") or "Week Recap"))
    paragraphs = result.get("paragraphs") or []
    paragraphs_html = "\n".join(
        f"<p style='margin:0 0 10px 0;'>{html.escape(str(p))}</p>"
        for p in paragraphs[:4] if str(p).strip()
    )

    return f"""
<div class="card" style="padding:18px 20px;margin-bottom:20px;">
  <div style="font-size:10px;font-weight:800;letter-spacing:.1em;color:var(--accent);margin-bottom:6px;">FROM THE GROUP CHAT</div>
  <div style="font-size:18px;font-weight:800;margin-bottom:12px;line-height:1.25;">{headline}</div>
  <div style="font-size:13px;line-height:1.55;color:var(--text);" data-br-reveal-text>
    {paragraphs_html}
  </div>
</div>
"""


def _render_next_week_html(preview: dict, looking_ahead: str) -> str:
    """Render the 'Game of the Week' look-ahead card: a banner header, the
    matchup (with a projected win-prob bar when projections are available), the
    AI blurb (which carries the reason it was picked), availability chips (out /
    questionable / bye) with a freshness stamp, and an also-worth-watching row.
    Returns '' when there's nothing to show."""
    if not preview or not preview.get("game_of_the_week"):
        return ""

    g = preview["game_of_the_week"]
    wk = preview.get("next_week")
    title_lead = preview.get("round_label") if preview.get("is_playoff") else "Game of the Week"
    kicker = f"NEXT WEEK{f' · WEEK {wk}' if wk else ''}"
    # A prominent banner header instead of a small eyebrow, so the section reads
    # as the marquee matchup it is.
    header_html = (
        "<div class='br-gotw-head'>"
        f"<span class='br-gotw-kicker'>{html.escape(kicker)}</span>"
        f"<span class='br-gotw-title'><i class='fa-solid fa-fire' aria-hidden='true'></i>"
        f"<span>{html.escape(str(title_lead))}</span></span>"
        "</div>"
    )

    def _side(team: str, record: str, rank, avatar, proj, cls: str) -> str:
        rank_str = f"#{rank}" if rank else ""
        meta = " · ".join(x for x in [record, rank_str] if x)
        if avatar:
            av = (
                f"<img class='br-gotw-av' src='{html.escape(str(avatar), quote=True)}' alt='' "
                "loading='lazy' decoding='async' onerror=\"this.style.display='none'\">"
            )
        else:
            # Initial-crest fallback so the layout stays balanced without a picture.
            initial = html.escape((str(team).strip()[:1] or "?").upper())
            av = f"<div class='br-gotw-av br-gotw-av-ph'>{initial}</div>"
        proj_html = (
            f"<div class='br-gotw-proj'>{proj:.1f} <span>proj</span></div>"
            if isinstance(proj, (int, float)) else ""
        )
        txt = (
            "<div class='br-gotw-side-txt'>"
            f"<div class='br-gotw-name'>{html.escape(str(team))}</div>"
            f"<div class='br-gotw-meta'>{html.escape(meta)}</div>"
            f"{proj_html}"
            "</div>"
        )
        return f"<div class='{cls} br-gotw-side'>{av}{txt}</div>"

    matchup_row = (
        "<div class='br-gotw-matchup'>"
        + _side(g["team_a"], g["record_a"], g["rank_a"], g.get("avatar_a"), g.get("proj_a"), "br-gotw-l")
        + "<div class='br-gotw-vs'>VS</div>"
        + _side(g["team_b"], g["record_b"], g["rank_b"], g.get("avatar_b"), g.get("proj_b"), "br-gotw-r")
        + "</div>"
    )

    # Projected win-probability bar (only when projections were available).
    wp = g.get("win_prob_a")
    winbar_html = ""
    if wp is not None:
        rp = 100 - wp
        winbar_html = (
            "<div style='display:flex;align-items:center;gap:8px;margin-bottom:12px;'>"
            f"<span style='font-size:11px;font-weight:800;color:var(--muted);flex:0 0 auto;'>{wp}%</span>"
            "<div style='flex:1;height:6px;border-radius:3px;overflow:hidden;"
            f"background:linear-gradient(to right,var(--accent) {wp}%,rgba(148,163,184,0.35) {wp}%);'></div>"
            f"<span style='font-size:11px;font-weight:800;color:var(--muted);flex:0 0 auto;'>{rp}%</span>"
            "</div>"
        )

    blurb_html = ""
    if looking_ahead and str(looking_ahead).strip():
        blurb_html = (
            f"<p style='margin:0 0 12px 0;font-size:13px;line-height:1.55;color:var(--text);'>"
            f"{html.escape(str(looking_ahead))}</p>"
        )

    # Availability chips: out (red) / questionable (amber) / bye (muted), each
    # with the player's projected points so "big" is visible.
    def _chip(p, cls, icon):
        proj = p.get("proj")
        pts = f" · {proj:g} pts" if isinstance(proj, (int, float)) and proj else ""
        label = f"{p.get('name')} ({p.get('status')}){pts}"
        return (
            f"<span class='player-badge {cls}' style='font-size:10px;'>"
            f"<i class='fa-solid {icon}' aria-hidden='true'></i> {html.escape(label)}</span>"
        )

    chips = []
    for side in ("a", "b"):
        for p in (g.get(f"out_{side}") or [])[:2]:
            chips.append(_chip(p, "player-badge-inj-out", "fa-triangle-exclamation"))
        # Icon classes must exist in the self-hosted Font Awesome subset
        # (static/font-awesome.css) or they silently render as nothing.
        for p in (g.get(f"maybe_{side}") or [])[:1]:
            chips.append(_chip(p, "player-badge-inj-q", "fa-circle-info"))
        for p in (g.get(f"bye_{side}") or [])[:1]:
            chips.append(_chip(p, "player-badge-inj-note", "fa-calendar-days"))
    avail_html = ""
    if chips:
        stamp = preview.get("as_of")
        stamp_html = (
            f"<span style='font-size:10px;color:var(--muted);margin-left:2px;'>availability as of {html.escape(str(stamp))}</span>"
            if stamp else ""
        )
        avail_html = (
            "<div style='display:flex;flex-wrap:wrap;align-items:center;gap:6px;margin-bottom:10px;'>"
            + "".join(chips) + stamp_html + "</div>"
        )

    # Also-worth-watching, each with its own one-word why. A near-tied runner-up
    # is flagged as a co-headliner.
    also = preview.get("also_watch") or []
    also_html = ""
    if also:
        label = "Co-game of the week" if preview.get("close_second") else "Also worth watching"
        items = " &nbsp;·&nbsp; ".join(
            f"{html.escape(str(a['team_a']))} vs {html.escape(str(a['team_b']))} "
            f"<span style='opacity:.75;'>({html.escape(str(a.get('why') or ''))})</span>"
            for a in also
        )
        also_html = (
            f"<div style='font-size:11px;color:var(--muted);border-top:1px solid var(--border,"
            f"rgba(148,163,184,0.2));padding-top:10px;'>{label}: {items}</div>"
        )

    return f"""
<div class="card br-gotw" data-br-moment="gotw" style="padding:18px 20px;margin-bottom:20px;">
  <div class="br-gotw-flash" aria-hidden="true"></div>
  {header_html}
  {matchup_row}
  {winbar_html}
  {blurb_html}
  {avail_html}
  {also_html}
</div>
"""


def get_weekly_ai_recap(
        df_weekly: pd.DataFrame,
        matchups_by_week: dict,
        selected_week: int,
        team_by_rid: dict,
        league: dict,
        league_id: str,
        season,
        next_week_ctx: dict | None = None,
) -> tuple[str, str]:
    """Return (recap_column_html, next_week_card_html). Either may be ''.

    Both are produced by one AI call and cached together under one key (split on a
    sentinel) so the group-chat recap and the game-of-the-week look-ahead stay in
    sync and never cost two round-trips."""
    empty = ("", "")
    if df_weekly is None or df_weekly.empty:
        return empty

    cache_key = f"weekly_recap_{league_id}_{season}_w{selected_week}_v10_chat"
    cached = _load_recap_no_ttl(cache_key)
    if cached is not None:
        recap_html, _, next_html = cached.partition(_NEXT_WEEK_SPLIT)
        return recap_html, next_html

    try:
        payload = build_weekly_recap_payload(
            df_weekly, matchups_by_week, selected_week, team_by_rid, league,
            next_week_ctx=next_week_ctx,
        )
    except Exception as exc:
        logger.warning("[weekly-recap] payload build failed: %s", exc)
        return empty

    if not ai_available():
        return empty  # silently skip when AI is off

    try:
        result = _generate_ai_storyline(payload)
        recap_html = _render_recap_html(result)
        next_html = _render_next_week_html(
            payload.get("next_week_preview"), result.get("looking_ahead") or "",
        )
        save_cached_ai_text(cache_key, recap_html + _NEXT_WEEK_SPLIT + next_html)
        return recap_html, next_html
    except (AIRateLimitError, AIUnavailableError) as exc:
        logger.warning("[weekly-recap] AI unavailable: %s", exc)
        return empty
    except Exception as exc:
        logger.warning("[weekly-recap] AI error: %s", exc)
        return empty


def get_weekly_ai_recap_preview() -> tuple[str, str]:
    """Static sample for preview mode: the recap column plus a game-of-the-week card."""
    recap_html = _render_recap_html({
        "headline": "Gridiron Ghosts got the rematch and it went worse than the first time",
        "paragraphs": [
            "Gridiron Ghosts lost to Dynasty Kings again. Week 7 rematch, same result, bigger margin this time. They're 0-2 against them on the season and the two losses account for the entire gap between their records. Not ideal.",
            "Slim Reaper Lemonade is doing that thing where they keep putting up big scores and losing anyway. Top-three scorer three weeks in a row, 1-2 in that stretch. Their points total is second in the league and they're sitting at 3-4. At some point that has to even out.",
            "Three teams are tied at 4-3 with five weeks left and two of them play each other in Week 8. Someone's going to separate. The bubble is real and a couple people in this league haven't fully processed that yet.",
            "Also JiggyJay30 scored 98 this week after putting up 134 last week. No notes. Fantasy is what it is.",
        ],
    })
    next_html = _render_next_week_html(
        {
            "next_week": 8,
            "is_playoff": False,
            "round_label": None,
            "weeks_left_after": 5,
            "quiet_week": False,
            "close_second": False,
            "as_of": "Tue Nov 4",
            "game_of_the_week": {
                "team_a": "Dynasty Kings", "team_b": "Blitz Brigade",
                "record_a": "6-1", "record_b": "5-2",
                "rank_a": 1, "rank_b": 3,
                "streak_a": "W4", "streak_b": "W2",
                "win_prob_a": 58,
                "h2h": {"meetings": 1, "a_wins": 1, "b_wins": 0},
                "out_a": [], "maybe_a": [], "bye_a": [],
                "out_b": [{"name": "Bijan Robinson", "pos": "RB", "status": "OUT", "proj": 19.4, "value": 8000}],
                "maybe_b": [], "bye_b": [],
                "why": "Two of the top teams, head to head", "top_factor": "strength",
                "reasons": ["two of the league's best", "a rematch", "Bijan Robinson (OUT) in doubt"],
                "score": 2.31,
            },
            "also_watch": [
                {"team_a": "Redzone Rebels", "team_b": "Endzone Elite",
                 "why": "Dead heat on paper (51-49)"},
            ],
        },
        "Top two teams next week, and Dynasty Kings already have the head-to-head after taking the first one. "
        "Blitz Brigade draws it without Bijan Robinson (OUT), so they're hunting for points somewhere. "
        "Kings haven't lost since that first meeting, and if Blitz can't cover the gap the top of the standings starts to run away.",
    )
    return recap_html, next_html
